// Code generated by ent, DO NOT EDIT.

package test3schema

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the test3schema type in the database.
	Label = "test3schema"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSku holds the string denoting the sku field in the database.
	FieldSku = "sku"
	// FieldProductName holds the string denoting the product_name field in the database.
	FieldProductName = "product_name"
	// FieldShortDescription holds the string denoting the short_description field in the database.
	FieldShortDescription = "short_description"
	// FieldFullDescription holds the string denoting the full_description field in the database.
	FieldFullDescription = "full_description"
	// FieldCostPrice holds the string denoting the cost_price field in the database.
	FieldCostPrice = "cost_price"
	// FieldRetailPrice holds the string denoting the retail_price field in the database.
	FieldRetailPrice = "retail_price"
	// FieldStockCount holds the string denoting the stock_count field in the database.
	FieldStockCount = "stock_count"
	// FieldIsActive holds the string denoting the is_active field in the database.
	FieldIsActive = "is_active"
	// FieldPublishedAt holds the string denoting the published_at field in the database.
	FieldPublishedAt = "published_at"
	// FieldLastOrderedAt holds the string denoting the last_ordered_at field in the database.
	FieldLastOrderedAt = "last_ordered_at"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// Table holds the table name of the test3schema in the database.
	Table = "test3schemas"
)

// Columns holds all SQL columns for test3schema fields.
var Columns = []string{
	FieldID,
	FieldSku,
	FieldProductName,
	FieldShortDescription,
	FieldFullDescription,
	FieldCostPrice,
	FieldRetailPrice,
	FieldStockCount,
	FieldIsActive,
	FieldPublishedAt,
	FieldLastOrderedAt,
	FieldTags,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// SkuValidator is a validator for the "sku" field. It is called by the builders before save.
	SkuValidator func(string) error
	// DefaultProductName holds the default value on creation for the "product_name" field.
	DefaultProductName string
	// DefaultCostPrice holds the default value on creation for the "cost_price" field.
	DefaultCostPrice float64
	// DefaultRetailPrice holds the default value on creation for the "retail_price" field.
	DefaultRetailPrice float64
	// DefaultStockCount holds the default value on creation for the "stock_count" field.
	DefaultStockCount int
	// DefaultIsActive holds the default value on creation for the "is_active" field.
	DefaultIsActive bool
)

// OrderOption defines the ordering options for the Test3Schema queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySku orders the results by the sku field.
func BySku(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSku, opts...).ToFunc()
}

// ByProductName orders the results by the product_name field.
func ByProductName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductName, opts...).ToFunc()
}

// ByShortDescription orders the results by the short_description field.
func ByShortDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldShortDescription, opts...).ToFunc()
}

// ByFullDescription orders the results by the full_description field.
func ByFullDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFullDescription, opts...).ToFunc()
}

// ByCostPrice orders the results by the cost_price field.
func ByCostPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCostPrice, opts...).ToFunc()
}

// ByRetailPrice orders the results by the retail_price field.
func ByRetailPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRetailPrice, opts...).ToFunc()
}

// ByStockCount orders the results by the stock_count field.
func ByStockCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStockCount, opts...).ToFunc()
}

// ByIsActive orders the results by the is_active field.
func ByIsActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsActive, opts...).ToFunc()
}

// ByPublishedAt orders the results by the published_at field.
func ByPublishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublishedAt, opts...).ToFunc()
}

// ByLastOrderedAt orders the results by the last_ordered_at field.
func ByLastOrderedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastOrderedAt, opts...).ToFunc()
}

// ByTags orders the results by the tags field.
func ByTags(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTags, opts...).ToFunc()
}
