// Code generated by ent, DO NOT EDIT.

package test3schema

import (
	"time"
	"transaction-filter-backend/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldLTE(FieldID, id))
}

// Sku applies equality check predicate on the "sku" field. It's identical to SkuEQ.
func Sku(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldEQ(FieldSku, v))
}

// ProductName applies equality check predicate on the "product_name" field. It's identical to ProductNameEQ.
func ProductName(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldEQ(FieldProductName, v))
}

// ShortDescription applies equality check predicate on the "short_description" field. It's identical to ShortDescriptionEQ.
func ShortDescription(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldEQ(FieldShortDescription, v))
}

// FullDescription applies equality check predicate on the "full_description" field. It's identical to FullDescriptionEQ.
func FullDescription(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldEQ(FieldFullDescription, v))
}

// CostPrice applies equality check predicate on the "cost_price" field. It's identical to CostPriceEQ.
func CostPrice(v float64) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldEQ(FieldCostPrice, v))
}

// RetailPrice applies equality check predicate on the "retail_price" field. It's identical to RetailPriceEQ.
func RetailPrice(v float64) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldEQ(FieldRetailPrice, v))
}

// StockCount applies equality check predicate on the "stock_count" field. It's identical to StockCountEQ.
func StockCount(v int) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldEQ(FieldStockCount, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldEQ(FieldIsActive, v))
}

// PublishedAt applies equality check predicate on the "published_at" field. It's identical to PublishedAtEQ.
func PublishedAt(v time.Time) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldEQ(FieldPublishedAt, v))
}

// LastOrderedAt applies equality check predicate on the "last_ordered_at" field. It's identical to LastOrderedAtEQ.
func LastOrderedAt(v time.Time) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldEQ(FieldLastOrderedAt, v))
}

// Tags applies equality check predicate on the "tags" field. It's identical to TagsEQ.
func Tags(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldEQ(FieldTags, v))
}

// SkuEQ applies the EQ predicate on the "sku" field.
func SkuEQ(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldEQ(FieldSku, v))
}

// SkuNEQ applies the NEQ predicate on the "sku" field.
func SkuNEQ(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldNEQ(FieldSku, v))
}

// SkuIn applies the In predicate on the "sku" field.
func SkuIn(vs ...string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldIn(FieldSku, vs...))
}

// SkuNotIn applies the NotIn predicate on the "sku" field.
func SkuNotIn(vs ...string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldNotIn(FieldSku, vs...))
}

// SkuGT applies the GT predicate on the "sku" field.
func SkuGT(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldGT(FieldSku, v))
}

// SkuGTE applies the GTE predicate on the "sku" field.
func SkuGTE(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldGTE(FieldSku, v))
}

// SkuLT applies the LT predicate on the "sku" field.
func SkuLT(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldLT(FieldSku, v))
}

// SkuLTE applies the LTE predicate on the "sku" field.
func SkuLTE(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldLTE(FieldSku, v))
}

// SkuContains applies the Contains predicate on the "sku" field.
func SkuContains(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldContains(FieldSku, v))
}

// SkuHasPrefix applies the HasPrefix predicate on the "sku" field.
func SkuHasPrefix(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldHasPrefix(FieldSku, v))
}

// SkuHasSuffix applies the HasSuffix predicate on the "sku" field.
func SkuHasSuffix(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldHasSuffix(FieldSku, v))
}

// SkuEqualFold applies the EqualFold predicate on the "sku" field.
func SkuEqualFold(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldEqualFold(FieldSku, v))
}

// SkuContainsFold applies the ContainsFold predicate on the "sku" field.
func SkuContainsFold(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldContainsFold(FieldSku, v))
}

// ProductNameEQ applies the EQ predicate on the "product_name" field.
func ProductNameEQ(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldEQ(FieldProductName, v))
}

// ProductNameNEQ applies the NEQ predicate on the "product_name" field.
func ProductNameNEQ(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldNEQ(FieldProductName, v))
}

// ProductNameIn applies the In predicate on the "product_name" field.
func ProductNameIn(vs ...string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldIn(FieldProductName, vs...))
}

// ProductNameNotIn applies the NotIn predicate on the "product_name" field.
func ProductNameNotIn(vs ...string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldNotIn(FieldProductName, vs...))
}

// ProductNameGT applies the GT predicate on the "product_name" field.
func ProductNameGT(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldGT(FieldProductName, v))
}

// ProductNameGTE applies the GTE predicate on the "product_name" field.
func ProductNameGTE(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldGTE(FieldProductName, v))
}

// ProductNameLT applies the LT predicate on the "product_name" field.
func ProductNameLT(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldLT(FieldProductName, v))
}

// ProductNameLTE applies the LTE predicate on the "product_name" field.
func ProductNameLTE(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldLTE(FieldProductName, v))
}

// ProductNameContains applies the Contains predicate on the "product_name" field.
func ProductNameContains(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldContains(FieldProductName, v))
}

// ProductNameHasPrefix applies the HasPrefix predicate on the "product_name" field.
func ProductNameHasPrefix(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldHasPrefix(FieldProductName, v))
}

// ProductNameHasSuffix applies the HasSuffix predicate on the "product_name" field.
func ProductNameHasSuffix(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldHasSuffix(FieldProductName, v))
}

// ProductNameEqualFold applies the EqualFold predicate on the "product_name" field.
func ProductNameEqualFold(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldEqualFold(FieldProductName, v))
}

// ProductNameContainsFold applies the ContainsFold predicate on the "product_name" field.
func ProductNameContainsFold(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldContainsFold(FieldProductName, v))
}

// ShortDescriptionEQ applies the EQ predicate on the "short_description" field.
func ShortDescriptionEQ(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldEQ(FieldShortDescription, v))
}

// ShortDescriptionNEQ applies the NEQ predicate on the "short_description" field.
func ShortDescriptionNEQ(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldNEQ(FieldShortDescription, v))
}

// ShortDescriptionIn applies the In predicate on the "short_description" field.
func ShortDescriptionIn(vs ...string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldIn(FieldShortDescription, vs...))
}

// ShortDescriptionNotIn applies the NotIn predicate on the "short_description" field.
func ShortDescriptionNotIn(vs ...string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldNotIn(FieldShortDescription, vs...))
}

// ShortDescriptionGT applies the GT predicate on the "short_description" field.
func ShortDescriptionGT(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldGT(FieldShortDescription, v))
}

// ShortDescriptionGTE applies the GTE predicate on the "short_description" field.
func ShortDescriptionGTE(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldGTE(FieldShortDescription, v))
}

// ShortDescriptionLT applies the LT predicate on the "short_description" field.
func ShortDescriptionLT(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldLT(FieldShortDescription, v))
}

// ShortDescriptionLTE applies the LTE predicate on the "short_description" field.
func ShortDescriptionLTE(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldLTE(FieldShortDescription, v))
}

// ShortDescriptionContains applies the Contains predicate on the "short_description" field.
func ShortDescriptionContains(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldContains(FieldShortDescription, v))
}

// ShortDescriptionHasPrefix applies the HasPrefix predicate on the "short_description" field.
func ShortDescriptionHasPrefix(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldHasPrefix(FieldShortDescription, v))
}

// ShortDescriptionHasSuffix applies the HasSuffix predicate on the "short_description" field.
func ShortDescriptionHasSuffix(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldHasSuffix(FieldShortDescription, v))
}

// ShortDescriptionIsNil applies the IsNil predicate on the "short_description" field.
func ShortDescriptionIsNil() predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldIsNull(FieldShortDescription))
}

// ShortDescriptionNotNil applies the NotNil predicate on the "short_description" field.
func ShortDescriptionNotNil() predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldNotNull(FieldShortDescription))
}

// ShortDescriptionEqualFold applies the EqualFold predicate on the "short_description" field.
func ShortDescriptionEqualFold(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldEqualFold(FieldShortDescription, v))
}

// ShortDescriptionContainsFold applies the ContainsFold predicate on the "short_description" field.
func ShortDescriptionContainsFold(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldContainsFold(FieldShortDescription, v))
}

// FullDescriptionEQ applies the EQ predicate on the "full_description" field.
func FullDescriptionEQ(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldEQ(FieldFullDescription, v))
}

// FullDescriptionNEQ applies the NEQ predicate on the "full_description" field.
func FullDescriptionNEQ(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldNEQ(FieldFullDescription, v))
}

// FullDescriptionIn applies the In predicate on the "full_description" field.
func FullDescriptionIn(vs ...string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldIn(FieldFullDescription, vs...))
}

// FullDescriptionNotIn applies the NotIn predicate on the "full_description" field.
func FullDescriptionNotIn(vs ...string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldNotIn(FieldFullDescription, vs...))
}

// FullDescriptionGT applies the GT predicate on the "full_description" field.
func FullDescriptionGT(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldGT(FieldFullDescription, v))
}

// FullDescriptionGTE applies the GTE predicate on the "full_description" field.
func FullDescriptionGTE(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldGTE(FieldFullDescription, v))
}

// FullDescriptionLT applies the LT predicate on the "full_description" field.
func FullDescriptionLT(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldLT(FieldFullDescription, v))
}

// FullDescriptionLTE applies the LTE predicate on the "full_description" field.
func FullDescriptionLTE(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldLTE(FieldFullDescription, v))
}

// FullDescriptionContains applies the Contains predicate on the "full_description" field.
func FullDescriptionContains(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldContains(FieldFullDescription, v))
}

// FullDescriptionHasPrefix applies the HasPrefix predicate on the "full_description" field.
func FullDescriptionHasPrefix(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldHasPrefix(FieldFullDescription, v))
}

// FullDescriptionHasSuffix applies the HasSuffix predicate on the "full_description" field.
func FullDescriptionHasSuffix(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldHasSuffix(FieldFullDescription, v))
}

// FullDescriptionIsNil applies the IsNil predicate on the "full_description" field.
func FullDescriptionIsNil() predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldIsNull(FieldFullDescription))
}

// FullDescriptionNotNil applies the NotNil predicate on the "full_description" field.
func FullDescriptionNotNil() predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldNotNull(FieldFullDescription))
}

// FullDescriptionEqualFold applies the EqualFold predicate on the "full_description" field.
func FullDescriptionEqualFold(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldEqualFold(FieldFullDescription, v))
}

// FullDescriptionContainsFold applies the ContainsFold predicate on the "full_description" field.
func FullDescriptionContainsFold(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldContainsFold(FieldFullDescription, v))
}

// CostPriceEQ applies the EQ predicate on the "cost_price" field.
func CostPriceEQ(v float64) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldEQ(FieldCostPrice, v))
}

// CostPriceNEQ applies the NEQ predicate on the "cost_price" field.
func CostPriceNEQ(v float64) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldNEQ(FieldCostPrice, v))
}

// CostPriceIn applies the In predicate on the "cost_price" field.
func CostPriceIn(vs ...float64) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldIn(FieldCostPrice, vs...))
}

// CostPriceNotIn applies the NotIn predicate on the "cost_price" field.
func CostPriceNotIn(vs ...float64) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldNotIn(FieldCostPrice, vs...))
}

// CostPriceGT applies the GT predicate on the "cost_price" field.
func CostPriceGT(v float64) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldGT(FieldCostPrice, v))
}

// CostPriceGTE applies the GTE predicate on the "cost_price" field.
func CostPriceGTE(v float64) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldGTE(FieldCostPrice, v))
}

// CostPriceLT applies the LT predicate on the "cost_price" field.
func CostPriceLT(v float64) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldLT(FieldCostPrice, v))
}

// CostPriceLTE applies the LTE predicate on the "cost_price" field.
func CostPriceLTE(v float64) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldLTE(FieldCostPrice, v))
}

// RetailPriceEQ applies the EQ predicate on the "retail_price" field.
func RetailPriceEQ(v float64) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldEQ(FieldRetailPrice, v))
}

// RetailPriceNEQ applies the NEQ predicate on the "retail_price" field.
func RetailPriceNEQ(v float64) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldNEQ(FieldRetailPrice, v))
}

// RetailPriceIn applies the In predicate on the "retail_price" field.
func RetailPriceIn(vs ...float64) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldIn(FieldRetailPrice, vs...))
}

// RetailPriceNotIn applies the NotIn predicate on the "retail_price" field.
func RetailPriceNotIn(vs ...float64) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldNotIn(FieldRetailPrice, vs...))
}

// RetailPriceGT applies the GT predicate on the "retail_price" field.
func RetailPriceGT(v float64) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldGT(FieldRetailPrice, v))
}

// RetailPriceGTE applies the GTE predicate on the "retail_price" field.
func RetailPriceGTE(v float64) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldGTE(FieldRetailPrice, v))
}

// RetailPriceLT applies the LT predicate on the "retail_price" field.
func RetailPriceLT(v float64) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldLT(FieldRetailPrice, v))
}

// RetailPriceLTE applies the LTE predicate on the "retail_price" field.
func RetailPriceLTE(v float64) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldLTE(FieldRetailPrice, v))
}

// StockCountEQ applies the EQ predicate on the "stock_count" field.
func StockCountEQ(v int) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldEQ(FieldStockCount, v))
}

// StockCountNEQ applies the NEQ predicate on the "stock_count" field.
func StockCountNEQ(v int) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldNEQ(FieldStockCount, v))
}

// StockCountIn applies the In predicate on the "stock_count" field.
func StockCountIn(vs ...int) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldIn(FieldStockCount, vs...))
}

// StockCountNotIn applies the NotIn predicate on the "stock_count" field.
func StockCountNotIn(vs ...int) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldNotIn(FieldStockCount, vs...))
}

// StockCountGT applies the GT predicate on the "stock_count" field.
func StockCountGT(v int) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldGT(FieldStockCount, v))
}

// StockCountGTE applies the GTE predicate on the "stock_count" field.
func StockCountGTE(v int) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldGTE(FieldStockCount, v))
}

// StockCountLT applies the LT predicate on the "stock_count" field.
func StockCountLT(v int) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldLT(FieldStockCount, v))
}

// StockCountLTE applies the LTE predicate on the "stock_count" field.
func StockCountLTE(v int) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldLTE(FieldStockCount, v))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldNEQ(FieldIsActive, v))
}

// PublishedAtEQ applies the EQ predicate on the "published_at" field.
func PublishedAtEQ(v time.Time) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldEQ(FieldPublishedAt, v))
}

// PublishedAtNEQ applies the NEQ predicate on the "published_at" field.
func PublishedAtNEQ(v time.Time) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldNEQ(FieldPublishedAt, v))
}

// PublishedAtIn applies the In predicate on the "published_at" field.
func PublishedAtIn(vs ...time.Time) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldIn(FieldPublishedAt, vs...))
}

// PublishedAtNotIn applies the NotIn predicate on the "published_at" field.
func PublishedAtNotIn(vs ...time.Time) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldNotIn(FieldPublishedAt, vs...))
}

// PublishedAtGT applies the GT predicate on the "published_at" field.
func PublishedAtGT(v time.Time) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldGT(FieldPublishedAt, v))
}

// PublishedAtGTE applies the GTE predicate on the "published_at" field.
func PublishedAtGTE(v time.Time) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldGTE(FieldPublishedAt, v))
}

// PublishedAtLT applies the LT predicate on the "published_at" field.
func PublishedAtLT(v time.Time) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldLT(FieldPublishedAt, v))
}

// PublishedAtLTE applies the LTE predicate on the "published_at" field.
func PublishedAtLTE(v time.Time) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldLTE(FieldPublishedAt, v))
}

// PublishedAtIsNil applies the IsNil predicate on the "published_at" field.
func PublishedAtIsNil() predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldIsNull(FieldPublishedAt))
}

// PublishedAtNotNil applies the NotNil predicate on the "published_at" field.
func PublishedAtNotNil() predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldNotNull(FieldPublishedAt))
}

// LastOrderedAtEQ applies the EQ predicate on the "last_ordered_at" field.
func LastOrderedAtEQ(v time.Time) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldEQ(FieldLastOrderedAt, v))
}

// LastOrderedAtNEQ applies the NEQ predicate on the "last_ordered_at" field.
func LastOrderedAtNEQ(v time.Time) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldNEQ(FieldLastOrderedAt, v))
}

// LastOrderedAtIn applies the In predicate on the "last_ordered_at" field.
func LastOrderedAtIn(vs ...time.Time) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldIn(FieldLastOrderedAt, vs...))
}

// LastOrderedAtNotIn applies the NotIn predicate on the "last_ordered_at" field.
func LastOrderedAtNotIn(vs ...time.Time) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldNotIn(FieldLastOrderedAt, vs...))
}

// LastOrderedAtGT applies the GT predicate on the "last_ordered_at" field.
func LastOrderedAtGT(v time.Time) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldGT(FieldLastOrderedAt, v))
}

// LastOrderedAtGTE applies the GTE predicate on the "last_ordered_at" field.
func LastOrderedAtGTE(v time.Time) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldGTE(FieldLastOrderedAt, v))
}

// LastOrderedAtLT applies the LT predicate on the "last_ordered_at" field.
func LastOrderedAtLT(v time.Time) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldLT(FieldLastOrderedAt, v))
}

// LastOrderedAtLTE applies the LTE predicate on the "last_ordered_at" field.
func LastOrderedAtLTE(v time.Time) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldLTE(FieldLastOrderedAt, v))
}

// LastOrderedAtIsNil applies the IsNil predicate on the "last_ordered_at" field.
func LastOrderedAtIsNil() predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldIsNull(FieldLastOrderedAt))
}

// LastOrderedAtNotNil applies the NotNil predicate on the "last_ordered_at" field.
func LastOrderedAtNotNil() predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldNotNull(FieldLastOrderedAt))
}

// TagsEQ applies the EQ predicate on the "tags" field.
func TagsEQ(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldEQ(FieldTags, v))
}

// TagsNEQ applies the NEQ predicate on the "tags" field.
func TagsNEQ(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldNEQ(FieldTags, v))
}

// TagsIn applies the In predicate on the "tags" field.
func TagsIn(vs ...string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldIn(FieldTags, vs...))
}

// TagsNotIn applies the NotIn predicate on the "tags" field.
func TagsNotIn(vs ...string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldNotIn(FieldTags, vs...))
}

// TagsGT applies the GT predicate on the "tags" field.
func TagsGT(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldGT(FieldTags, v))
}

// TagsGTE applies the GTE predicate on the "tags" field.
func TagsGTE(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldGTE(FieldTags, v))
}

// TagsLT applies the LT predicate on the "tags" field.
func TagsLT(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldLT(FieldTags, v))
}

// TagsLTE applies the LTE predicate on the "tags" field.
func TagsLTE(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldLTE(FieldTags, v))
}

// TagsContains applies the Contains predicate on the "tags" field.
func TagsContains(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldContains(FieldTags, v))
}

// TagsHasPrefix applies the HasPrefix predicate on the "tags" field.
func TagsHasPrefix(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldHasPrefix(FieldTags, v))
}

// TagsHasSuffix applies the HasSuffix predicate on the "tags" field.
func TagsHasSuffix(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldHasSuffix(FieldTags, v))
}

// TagsIsNil applies the IsNil predicate on the "tags" field.
func TagsIsNil() predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldIsNull(FieldTags))
}

// TagsNotNil applies the NotNil predicate on the "tags" field.
func TagsNotNil() predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldNotNull(FieldTags))
}

// TagsEqualFold applies the EqualFold predicate on the "tags" field.
func TagsEqualFold(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldEqualFold(FieldTags, v))
}

// TagsContainsFold applies the ContainsFold predicate on the "tags" field.
func TagsContainsFold(v string) predicate.Test3Schema {
	return predicate.Test3Schema(sql.FieldContainsFold(FieldTags, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Test3Schema) predicate.Test3Schema {
	return predicate.Test3Schema(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Test3Schema) predicate.Test3Schema {
	return predicate.Test3Schema(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Test3Schema) predicate.Test3Schema {
	return predicate.Test3Schema(sql.NotPredicates(p))
}
