// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// Test1schemasColumns holds the columns for the "test1schemas" table.
	Test1schemasColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "field_string", Type: field.TypeString, Default: "default string"},
		{Name: "field_int", Type: field.TypeInt, Default: 0},
		{Name: "field_float", Type: field.TypeFloat64, Default: 0},
		{Name: "field_bool", Type: field.TypeBool, Default: false},
		{Name: "field_time", Type: field.TypeTime},
		{Name: "field_text", Type: field.TypeString, Nullable: true, Size: 2147483647},
	}
	// Test1schemasTable holds the schema information for the "test1schemas" table.
	Test1schemasTable = &schema.Table{
		Name:       "test1schemas",
		Columns:    Test1schemasColumns,
		PrimaryKey: []*schema.Column{Test1schemasColumns[0]},
	}
	// Test2schemasColumns holds the columns for the "test2schemas" table.
	Test2schemasColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Default: "Unknown Name"},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "quantity", Type: field.TypeInt, Default: 0},
		{Name: "price", Type: field.TypeFloat64, Default: 0},
		{Name: "active", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "item_type", Type: field.TypeString, Nullable: true},
	}
	// Test2schemasTable holds the schema information for the "test2schemas" table.
	Test2schemasTable = &schema.Table{
		Name:       "test2schemas",
		Columns:    Test2schemasColumns,
		PrimaryKey: []*schema.Column{Test2schemasColumns[0]},
	}
	// Test3schemasColumns holds the columns for the "test3schemas" table.
	Test3schemasColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "sku", Type: field.TypeString, Unique: true},
		{Name: "product_name", Type: field.TypeString, Default: "Unnamed Product"},
		{Name: "short_description", Type: field.TypeString, Nullable: true},
		{Name: "full_description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "cost_price", Type: field.TypeFloat64, Default: 0},
		{Name: "retail_price", Type: field.TypeFloat64, Default: 0},
		{Name: "stock_count", Type: field.TypeInt, Default: 0},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "published_at", Type: field.TypeTime, Nullable: true},
		{Name: "last_ordered_at", Type: field.TypeTime, Nullable: true},
		{Name: "tags", Type: field.TypeString, Nullable: true},
	}
	// Test3schemasTable holds the schema information for the "test3schemas" table.
	Test3schemasTable = &schema.Table{
		Name:       "test3schemas",
		Columns:    Test3schemasColumns,
		PrimaryKey: []*schema.Column{Test3schemasColumns[0]},
	}
	// TransactionsColumns holds the columns for the "transactions" table.
	TransactionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "date", Type: field.TypeTime},
		{Name: "amount", Type: field.TypeFloat64},
		{Name: "name", Type: field.TypeString},
		{Name: "location", Type: field.TypeString},
		{Name: "category", Type: field.TypeString},
		{Name: "type", Type: field.TypeString},
	}
	// TransactionsTable holds the schema information for the "transactions" table.
	TransactionsTable = &schema.Table{
		Name:       "transactions",
		Columns:    TransactionsColumns,
		PrimaryKey: []*schema.Column{TransactionsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		Test1schemasTable,
		Test2schemasTable,
		Test3schemasTable,
		TransactionsTable,
	}
)

func init() {
}
