// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"transaction-filter-backend/ent/migrate"

	"transaction-filter-backend/ent/test1schema"
	"transaction-filter-backend/ent/test2schema"
	"transaction-filter-backend/ent/test3schema"
	"transaction-filter-backend/ent/transaction"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Test1Schema is the client for interacting with the Test1Schema builders.
	Test1Schema *Test1SchemaClient
	// Test2Schema is the client for interacting with the Test2Schema builders.
	Test2Schema *Test2SchemaClient
	// Test3Schema is the client for interacting with the Test3Schema builders.
	Test3Schema *Test3SchemaClient
	// Transaction is the client for interacting with the Transaction builders.
	Transaction *TransactionClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Test1Schema = NewTest1SchemaClient(c.config)
	c.Test2Schema = NewTest2SchemaClient(c.config)
	c.Test3Schema = NewTest3SchemaClient(c.config)
	c.Transaction = NewTransactionClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:         ctx,
		config:      cfg,
		Test1Schema: NewTest1SchemaClient(cfg),
		Test2Schema: NewTest2SchemaClient(cfg),
		Test3Schema: NewTest3SchemaClient(cfg),
		Transaction: NewTransactionClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:         ctx,
		config:      cfg,
		Test1Schema: NewTest1SchemaClient(cfg),
		Test2Schema: NewTest2SchemaClient(cfg),
		Test3Schema: NewTest3SchemaClient(cfg),
		Transaction: NewTransactionClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Test1Schema.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Test1Schema.Use(hooks...)
	c.Test2Schema.Use(hooks...)
	c.Test3Schema.Use(hooks...)
	c.Transaction.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Test1Schema.Intercept(interceptors...)
	c.Test2Schema.Intercept(interceptors...)
	c.Test3Schema.Intercept(interceptors...)
	c.Transaction.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *Test1SchemaMutation:
		return c.Test1Schema.mutate(ctx, m)
	case *Test2SchemaMutation:
		return c.Test2Schema.mutate(ctx, m)
	case *Test3SchemaMutation:
		return c.Test3Schema.mutate(ctx, m)
	case *TransactionMutation:
		return c.Transaction.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// Test1SchemaClient is a client for the Test1Schema schema.
type Test1SchemaClient struct {
	config
}

// NewTest1SchemaClient returns a client for the Test1Schema from the given config.
func NewTest1SchemaClient(c config) *Test1SchemaClient {
	return &Test1SchemaClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `test1schema.Hooks(f(g(h())))`.
func (c *Test1SchemaClient) Use(hooks ...Hook) {
	c.hooks.Test1Schema = append(c.hooks.Test1Schema, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `test1schema.Intercept(f(g(h())))`.
func (c *Test1SchemaClient) Intercept(interceptors ...Interceptor) {
	c.inters.Test1Schema = append(c.inters.Test1Schema, interceptors...)
}

// Create returns a builder for creating a Test1Schema entity.
func (c *Test1SchemaClient) Create() *Test1SchemaCreate {
	mutation := newTest1SchemaMutation(c.config, OpCreate)
	return &Test1SchemaCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Test1Schema entities.
func (c *Test1SchemaClient) CreateBulk(builders ...*Test1SchemaCreate) *Test1SchemaCreateBulk {
	return &Test1SchemaCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *Test1SchemaClient) MapCreateBulk(slice any, setFunc func(*Test1SchemaCreate, int)) *Test1SchemaCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &Test1SchemaCreateBulk{err: fmt.Errorf("calling to Test1SchemaClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*Test1SchemaCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &Test1SchemaCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Test1Schema.
func (c *Test1SchemaClient) Update() *Test1SchemaUpdate {
	mutation := newTest1SchemaMutation(c.config, OpUpdate)
	return &Test1SchemaUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *Test1SchemaClient) UpdateOne(t *Test1Schema) *Test1SchemaUpdateOne {
	mutation := newTest1SchemaMutation(c.config, OpUpdateOne, withTest1Schema(t))
	return &Test1SchemaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *Test1SchemaClient) UpdateOneID(id int) *Test1SchemaUpdateOne {
	mutation := newTest1SchemaMutation(c.config, OpUpdateOne, withTest1SchemaID(id))
	return &Test1SchemaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Test1Schema.
func (c *Test1SchemaClient) Delete() *Test1SchemaDelete {
	mutation := newTest1SchemaMutation(c.config, OpDelete)
	return &Test1SchemaDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *Test1SchemaClient) DeleteOne(t *Test1Schema) *Test1SchemaDeleteOne {
	return c.DeleteOneID(t.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *Test1SchemaClient) DeleteOneID(id int) *Test1SchemaDeleteOne {
	builder := c.Delete().Where(test1schema.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &Test1SchemaDeleteOne{builder}
}

// Query returns a query builder for Test1Schema.
func (c *Test1SchemaClient) Query() *Test1SchemaQuery {
	return &Test1SchemaQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTest1Schema},
		inters: c.Interceptors(),
	}
}

// Get returns a Test1Schema entity by its id.
func (c *Test1SchemaClient) Get(ctx context.Context, id int) (*Test1Schema, error) {
	return c.Query().Where(test1schema.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *Test1SchemaClient) GetX(ctx context.Context, id int) *Test1Schema {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *Test1SchemaClient) Hooks() []Hook {
	return c.hooks.Test1Schema
}

// Interceptors returns the client interceptors.
func (c *Test1SchemaClient) Interceptors() []Interceptor {
	return c.inters.Test1Schema
}

func (c *Test1SchemaClient) mutate(ctx context.Context, m *Test1SchemaMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&Test1SchemaCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&Test1SchemaUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&Test1SchemaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&Test1SchemaDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Test1Schema mutation op: %q", m.Op())
	}
}

// Test2SchemaClient is a client for the Test2Schema schema.
type Test2SchemaClient struct {
	config
}

// NewTest2SchemaClient returns a client for the Test2Schema from the given config.
func NewTest2SchemaClient(c config) *Test2SchemaClient {
	return &Test2SchemaClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `test2schema.Hooks(f(g(h())))`.
func (c *Test2SchemaClient) Use(hooks ...Hook) {
	c.hooks.Test2Schema = append(c.hooks.Test2Schema, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `test2schema.Intercept(f(g(h())))`.
func (c *Test2SchemaClient) Intercept(interceptors ...Interceptor) {
	c.inters.Test2Schema = append(c.inters.Test2Schema, interceptors...)
}

// Create returns a builder for creating a Test2Schema entity.
func (c *Test2SchemaClient) Create() *Test2SchemaCreate {
	mutation := newTest2SchemaMutation(c.config, OpCreate)
	return &Test2SchemaCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Test2Schema entities.
func (c *Test2SchemaClient) CreateBulk(builders ...*Test2SchemaCreate) *Test2SchemaCreateBulk {
	return &Test2SchemaCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *Test2SchemaClient) MapCreateBulk(slice any, setFunc func(*Test2SchemaCreate, int)) *Test2SchemaCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &Test2SchemaCreateBulk{err: fmt.Errorf("calling to Test2SchemaClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*Test2SchemaCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &Test2SchemaCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Test2Schema.
func (c *Test2SchemaClient) Update() *Test2SchemaUpdate {
	mutation := newTest2SchemaMutation(c.config, OpUpdate)
	return &Test2SchemaUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *Test2SchemaClient) UpdateOne(t *Test2Schema) *Test2SchemaUpdateOne {
	mutation := newTest2SchemaMutation(c.config, OpUpdateOne, withTest2Schema(t))
	return &Test2SchemaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *Test2SchemaClient) UpdateOneID(id int) *Test2SchemaUpdateOne {
	mutation := newTest2SchemaMutation(c.config, OpUpdateOne, withTest2SchemaID(id))
	return &Test2SchemaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Test2Schema.
func (c *Test2SchemaClient) Delete() *Test2SchemaDelete {
	mutation := newTest2SchemaMutation(c.config, OpDelete)
	return &Test2SchemaDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *Test2SchemaClient) DeleteOne(t *Test2Schema) *Test2SchemaDeleteOne {
	return c.DeleteOneID(t.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *Test2SchemaClient) DeleteOneID(id int) *Test2SchemaDeleteOne {
	builder := c.Delete().Where(test2schema.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &Test2SchemaDeleteOne{builder}
}

// Query returns a query builder for Test2Schema.
func (c *Test2SchemaClient) Query() *Test2SchemaQuery {
	return &Test2SchemaQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTest2Schema},
		inters: c.Interceptors(),
	}
}

// Get returns a Test2Schema entity by its id.
func (c *Test2SchemaClient) Get(ctx context.Context, id int) (*Test2Schema, error) {
	return c.Query().Where(test2schema.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *Test2SchemaClient) GetX(ctx context.Context, id int) *Test2Schema {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *Test2SchemaClient) Hooks() []Hook {
	return c.hooks.Test2Schema
}

// Interceptors returns the client interceptors.
func (c *Test2SchemaClient) Interceptors() []Interceptor {
	return c.inters.Test2Schema
}

func (c *Test2SchemaClient) mutate(ctx context.Context, m *Test2SchemaMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&Test2SchemaCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&Test2SchemaUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&Test2SchemaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&Test2SchemaDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Test2Schema mutation op: %q", m.Op())
	}
}

// Test3SchemaClient is a client for the Test3Schema schema.
type Test3SchemaClient struct {
	config
}

// NewTest3SchemaClient returns a client for the Test3Schema from the given config.
func NewTest3SchemaClient(c config) *Test3SchemaClient {
	return &Test3SchemaClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `test3schema.Hooks(f(g(h())))`.
func (c *Test3SchemaClient) Use(hooks ...Hook) {
	c.hooks.Test3Schema = append(c.hooks.Test3Schema, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `test3schema.Intercept(f(g(h())))`.
func (c *Test3SchemaClient) Intercept(interceptors ...Interceptor) {
	c.inters.Test3Schema = append(c.inters.Test3Schema, interceptors...)
}

// Create returns a builder for creating a Test3Schema entity.
func (c *Test3SchemaClient) Create() *Test3SchemaCreate {
	mutation := newTest3SchemaMutation(c.config, OpCreate)
	return &Test3SchemaCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Test3Schema entities.
func (c *Test3SchemaClient) CreateBulk(builders ...*Test3SchemaCreate) *Test3SchemaCreateBulk {
	return &Test3SchemaCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *Test3SchemaClient) MapCreateBulk(slice any, setFunc func(*Test3SchemaCreate, int)) *Test3SchemaCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &Test3SchemaCreateBulk{err: fmt.Errorf("calling to Test3SchemaClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*Test3SchemaCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &Test3SchemaCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Test3Schema.
func (c *Test3SchemaClient) Update() *Test3SchemaUpdate {
	mutation := newTest3SchemaMutation(c.config, OpUpdate)
	return &Test3SchemaUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *Test3SchemaClient) UpdateOne(t *Test3Schema) *Test3SchemaUpdateOne {
	mutation := newTest3SchemaMutation(c.config, OpUpdateOne, withTest3Schema(t))
	return &Test3SchemaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *Test3SchemaClient) UpdateOneID(id int) *Test3SchemaUpdateOne {
	mutation := newTest3SchemaMutation(c.config, OpUpdateOne, withTest3SchemaID(id))
	return &Test3SchemaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Test3Schema.
func (c *Test3SchemaClient) Delete() *Test3SchemaDelete {
	mutation := newTest3SchemaMutation(c.config, OpDelete)
	return &Test3SchemaDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *Test3SchemaClient) DeleteOne(t *Test3Schema) *Test3SchemaDeleteOne {
	return c.DeleteOneID(t.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *Test3SchemaClient) DeleteOneID(id int) *Test3SchemaDeleteOne {
	builder := c.Delete().Where(test3schema.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &Test3SchemaDeleteOne{builder}
}

// Query returns a query builder for Test3Schema.
func (c *Test3SchemaClient) Query() *Test3SchemaQuery {
	return &Test3SchemaQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTest3Schema},
		inters: c.Interceptors(),
	}
}

// Get returns a Test3Schema entity by its id.
func (c *Test3SchemaClient) Get(ctx context.Context, id int) (*Test3Schema, error) {
	return c.Query().Where(test3schema.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *Test3SchemaClient) GetX(ctx context.Context, id int) *Test3Schema {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *Test3SchemaClient) Hooks() []Hook {
	return c.hooks.Test3Schema
}

// Interceptors returns the client interceptors.
func (c *Test3SchemaClient) Interceptors() []Interceptor {
	return c.inters.Test3Schema
}

func (c *Test3SchemaClient) mutate(ctx context.Context, m *Test3SchemaMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&Test3SchemaCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&Test3SchemaUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&Test3SchemaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&Test3SchemaDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Test3Schema mutation op: %q", m.Op())
	}
}

// TransactionClient is a client for the Transaction schema.
type TransactionClient struct {
	config
}

// NewTransactionClient returns a client for the Transaction from the given config.
func NewTransactionClient(c config) *TransactionClient {
	return &TransactionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `transaction.Hooks(f(g(h())))`.
func (c *TransactionClient) Use(hooks ...Hook) {
	c.hooks.Transaction = append(c.hooks.Transaction, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `transaction.Intercept(f(g(h())))`.
func (c *TransactionClient) Intercept(interceptors ...Interceptor) {
	c.inters.Transaction = append(c.inters.Transaction, interceptors...)
}

// Create returns a builder for creating a Transaction entity.
func (c *TransactionClient) Create() *TransactionCreate {
	mutation := newTransactionMutation(c.config, OpCreate)
	return &TransactionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Transaction entities.
func (c *TransactionClient) CreateBulk(builders ...*TransactionCreate) *TransactionCreateBulk {
	return &TransactionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TransactionClient) MapCreateBulk(slice any, setFunc func(*TransactionCreate, int)) *TransactionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TransactionCreateBulk{err: fmt.Errorf("calling to TransactionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TransactionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TransactionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Transaction.
func (c *TransactionClient) Update() *TransactionUpdate {
	mutation := newTransactionMutation(c.config, OpUpdate)
	return &TransactionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TransactionClient) UpdateOne(t *Transaction) *TransactionUpdateOne {
	mutation := newTransactionMutation(c.config, OpUpdateOne, withTransaction(t))
	return &TransactionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TransactionClient) UpdateOneID(id int) *TransactionUpdateOne {
	mutation := newTransactionMutation(c.config, OpUpdateOne, withTransactionID(id))
	return &TransactionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Transaction.
func (c *TransactionClient) Delete() *TransactionDelete {
	mutation := newTransactionMutation(c.config, OpDelete)
	return &TransactionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TransactionClient) DeleteOne(t *Transaction) *TransactionDeleteOne {
	return c.DeleteOneID(t.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TransactionClient) DeleteOneID(id int) *TransactionDeleteOne {
	builder := c.Delete().Where(transaction.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TransactionDeleteOne{builder}
}

// Query returns a query builder for Transaction.
func (c *TransactionClient) Query() *TransactionQuery {
	return &TransactionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTransaction},
		inters: c.Interceptors(),
	}
}

// Get returns a Transaction entity by its id.
func (c *TransactionClient) Get(ctx context.Context, id int) (*Transaction, error) {
	return c.Query().Where(transaction.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TransactionClient) GetX(ctx context.Context, id int) *Transaction {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *TransactionClient) Hooks() []Hook {
	return c.hooks.Transaction
}

// Interceptors returns the client interceptors.
func (c *TransactionClient) Interceptors() []Interceptor {
	return c.inters.Transaction
}

func (c *TransactionClient) mutate(ctx context.Context, m *TransactionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TransactionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TransactionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TransactionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TransactionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Transaction mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Test1Schema, Test2Schema, Test3Schema, Transaction []ent.Hook
	}
	inters struct {
		Test1Schema, Test2Schema, Test3Schema, Transaction []ent.Interceptor
	}
)
