// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"
	"transaction-filter-backend/ent/schema"
	"transaction-filter-backend/ent/test1schema"
	"transaction-filter-backend/ent/test2schema"
	"transaction-filter-backend/ent/test3schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	test1schemaFields := schema.Test1Schema{}.Fields()
	_ = test1schemaFields
	// test1schemaDescFieldString is the schema descriptor for field_string field.
	test1schemaDescFieldString := test1schemaFields[0].Descriptor()
	// test1schema.DefaultFieldString holds the default value on creation for the field_string field.
	test1schema.DefaultFieldString = test1schemaDescFieldString.Default.(string)
	// test1schemaDescFieldInt is the schema descriptor for field_int field.
	test1schemaDescFieldInt := test1schemaFields[1].Descriptor()
	// test1schema.DefaultFieldInt holds the default value on creation for the field_int field.
	test1schema.DefaultFieldInt = test1schemaDescFieldInt.Default.(int)
	// test1schemaDescFieldFloat is the schema descriptor for field_float field.
	test1schemaDescFieldFloat := test1schemaFields[2].Descriptor()
	// test1schema.DefaultFieldFloat holds the default value on creation for the field_float field.
	test1schema.DefaultFieldFloat = test1schemaDescFieldFloat.Default.(float64)
	// test1schemaDescFieldBool is the schema descriptor for field_bool field.
	test1schemaDescFieldBool := test1schemaFields[3].Descriptor()
	// test1schema.DefaultFieldBool holds the default value on creation for the field_bool field.
	test1schema.DefaultFieldBool = test1schemaDescFieldBool.Default.(bool)
	// test1schemaDescFieldTime is the schema descriptor for field_time field.
	test1schemaDescFieldTime := test1schemaFields[4].Descriptor()
	// test1schema.DefaultFieldTime holds the default value on creation for the field_time field.
	test1schema.DefaultFieldTime = test1schemaDescFieldTime.Default.(func() time.Time)
	test2schemaFields := schema.Test2Schema{}.Fields()
	_ = test2schemaFields
	// test2schemaDescName is the schema descriptor for name field.
	test2schemaDescName := test2schemaFields[0].Descriptor()
	// test2schema.DefaultName holds the default value on creation for the name field.
	test2schema.DefaultName = test2schemaDescName.Default.(string)
	// test2schemaDescQuantity is the schema descriptor for quantity field.
	test2schemaDescQuantity := test2schemaFields[2].Descriptor()
	// test2schema.DefaultQuantity holds the default value on creation for the quantity field.
	test2schema.DefaultQuantity = test2schemaDescQuantity.Default.(int)
	// test2schemaDescPrice is the schema descriptor for price field.
	test2schemaDescPrice := test2schemaFields[3].Descriptor()
	// test2schema.DefaultPrice holds the default value on creation for the price field.
	test2schema.DefaultPrice = test2schemaDescPrice.Default.(float64)
	// test2schemaDescActive is the schema descriptor for active field.
	test2schemaDescActive := test2schemaFields[4].Descriptor()
	// test2schema.DefaultActive holds the default value on creation for the active field.
	test2schema.DefaultActive = test2schemaDescActive.Default.(bool)
	// test2schemaDescCreatedAt is the schema descriptor for created_at field.
	test2schemaDescCreatedAt := test2schemaFields[5].Descriptor()
	// test2schema.DefaultCreatedAt holds the default value on creation for the created_at field.
	test2schema.DefaultCreatedAt = test2schemaDescCreatedAt.Default.(func() time.Time)
	// test2schemaDescUpdatedAt is the schema descriptor for updated_at field.
	test2schemaDescUpdatedAt := test2schemaFields[6].Descriptor()
	// test2schema.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	test2schema.DefaultUpdatedAt = test2schemaDescUpdatedAt.Default.(func() time.Time)
	// test2schema.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	test2schema.UpdateDefaultUpdatedAt = test2schemaDescUpdatedAt.UpdateDefault.(func() time.Time)
	test3schemaFields := schema.Test3Schema{}.Fields()
	_ = test3schemaFields
	// test3schemaDescSku is the schema descriptor for sku field.
	test3schemaDescSku := test3schemaFields[0].Descriptor()
	// test3schema.SkuValidator is a validator for the "sku" field. It is called by the builders before save.
	test3schema.SkuValidator = test3schemaDescSku.Validators[0].(func(string) error)
	// test3schemaDescProductName is the schema descriptor for product_name field.
	test3schemaDescProductName := test3schemaFields[1].Descriptor()
	// test3schema.DefaultProductName holds the default value on creation for the product_name field.
	test3schema.DefaultProductName = test3schemaDescProductName.Default.(string)
	// test3schemaDescCostPrice is the schema descriptor for cost_price field.
	test3schemaDescCostPrice := test3schemaFields[4].Descriptor()
	// test3schema.DefaultCostPrice holds the default value on creation for the cost_price field.
	test3schema.DefaultCostPrice = test3schemaDescCostPrice.Default.(float64)
	// test3schemaDescRetailPrice is the schema descriptor for retail_price field.
	test3schemaDescRetailPrice := test3schemaFields[5].Descriptor()
	// test3schema.DefaultRetailPrice holds the default value on creation for the retail_price field.
	test3schema.DefaultRetailPrice = test3schemaDescRetailPrice.Default.(float64)
	// test3schemaDescStockCount is the schema descriptor for stock_count field.
	test3schemaDescStockCount := test3schemaFields[6].Descriptor()
	// test3schema.DefaultStockCount holds the default value on creation for the stock_count field.
	test3schema.DefaultStockCount = test3schemaDescStockCount.Default.(int)
	// test3schemaDescIsActive is the schema descriptor for is_active field.
	test3schemaDescIsActive := test3schemaFields[7].Descriptor()
	// test3schema.DefaultIsActive holds the default value on creation for the is_active field.
	test3schema.DefaultIsActive = test3schemaDescIsActive.Default.(bool)
}
