// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"transaction-filter-backend/ent/predicate"
	"transaction-filter-backend/ent/test2schema"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// Test2SchemaQuery is the builder for querying Test2Schema entities.
type Test2SchemaQuery struct {
	config
	ctx        *QueryContext
	order      []test2schema.OrderOption
	inters     []Interceptor
	predicates []predicate.Test2Schema
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the Test2SchemaQuery builder.
func (tq *Test2SchemaQuery) Where(ps ...predicate.Test2Schema) *Test2SchemaQuery {
	tq.predicates = append(tq.predicates, ps...)
	return tq
}

// Limit the number of records to be returned by this query.
func (tq *Test2SchemaQuery) Limit(limit int) *Test2SchemaQuery {
	tq.ctx.Limit = &limit
	return tq
}

// Offset to start from.
func (tq *Test2SchemaQuery) Offset(offset int) *Test2SchemaQuery {
	tq.ctx.Offset = &offset
	return tq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tq *Test2SchemaQuery) Unique(unique bool) *Test2SchemaQuery {
	tq.ctx.Unique = &unique
	return tq
}

// Order specifies how the records should be ordered.
func (tq *Test2SchemaQuery) Order(o ...test2schema.OrderOption) *Test2SchemaQuery {
	tq.order = append(tq.order, o...)
	return tq
}

// First returns the first Test2Schema entity from the query.
// Returns a *NotFoundError when no Test2Schema was found.
func (tq *Test2SchemaQuery) First(ctx context.Context) (*Test2Schema, error) {
	nodes, err := tq.Limit(1).All(setContextOp(ctx, tq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{test2schema.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tq *Test2SchemaQuery) FirstX(ctx context.Context) *Test2Schema {
	node, err := tq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Test2Schema ID from the query.
// Returns a *NotFoundError when no Test2Schema ID was found.
func (tq *Test2SchemaQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tq.Limit(1).IDs(setContextOp(ctx, tq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{test2schema.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tq *Test2SchemaQuery) FirstIDX(ctx context.Context) int {
	id, err := tq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Test2Schema entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Test2Schema entity is found.
// Returns a *NotFoundError when no Test2Schema entities are found.
func (tq *Test2SchemaQuery) Only(ctx context.Context) (*Test2Schema, error) {
	nodes, err := tq.Limit(2).All(setContextOp(ctx, tq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{test2schema.Label}
	default:
		return nil, &NotSingularError{test2schema.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tq *Test2SchemaQuery) OnlyX(ctx context.Context) *Test2Schema {
	node, err := tq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Test2Schema ID in the query.
// Returns a *NotSingularError when more than one Test2Schema ID is found.
// Returns a *NotFoundError when no entities are found.
func (tq *Test2SchemaQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tq.Limit(2).IDs(setContextOp(ctx, tq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{test2schema.Label}
	default:
		err = &NotSingularError{test2schema.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tq *Test2SchemaQuery) OnlyIDX(ctx context.Context) int {
	id, err := tq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Test2Schemas.
func (tq *Test2SchemaQuery) All(ctx context.Context) ([]*Test2Schema, error) {
	ctx = setContextOp(ctx, tq.ctx, ent.OpQueryAll)
	if err := tq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Test2Schema, *Test2SchemaQuery]()
	return withInterceptors[[]*Test2Schema](ctx, tq, qr, tq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tq *Test2SchemaQuery) AllX(ctx context.Context) []*Test2Schema {
	nodes, err := tq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Test2Schema IDs.
func (tq *Test2SchemaQuery) IDs(ctx context.Context) (ids []int, err error) {
	if tq.ctx.Unique == nil && tq.path != nil {
		tq.Unique(true)
	}
	ctx = setContextOp(ctx, tq.ctx, ent.OpQueryIDs)
	if err = tq.Select(test2schema.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tq *Test2SchemaQuery) IDsX(ctx context.Context) []int {
	ids, err := tq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tq *Test2SchemaQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tq.ctx, ent.OpQueryCount)
	if err := tq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tq, querierCount[*Test2SchemaQuery](), tq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tq *Test2SchemaQuery) CountX(ctx context.Context) int {
	count, err := tq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tq *Test2SchemaQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tq.ctx, ent.OpQueryExist)
	switch _, err := tq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tq *Test2SchemaQuery) ExistX(ctx context.Context) bool {
	exist, err := tq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the Test2SchemaQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tq *Test2SchemaQuery) Clone() *Test2SchemaQuery {
	if tq == nil {
		return nil
	}
	return &Test2SchemaQuery{
		config:     tq.config,
		ctx:        tq.ctx.Clone(),
		order:      append([]test2schema.OrderOption{}, tq.order...),
		inters:     append([]Interceptor{}, tq.inters...),
		predicates: append([]predicate.Test2Schema{}, tq.predicates...),
		// clone intermediate query.
		sql:  tq.sql.Clone(),
		path: tq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Test2Schema.Query().
//		GroupBy(test2schema.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tq *Test2SchemaQuery) GroupBy(field string, fields ...string) *Test2SchemaGroupBy {
	tq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &Test2SchemaGroupBy{build: tq}
	grbuild.flds = &tq.ctx.Fields
	grbuild.label = test2schema.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.Test2Schema.Query().
//		Select(test2schema.FieldName).
//		Scan(ctx, &v)
func (tq *Test2SchemaQuery) Select(fields ...string) *Test2SchemaSelect {
	tq.ctx.Fields = append(tq.ctx.Fields, fields...)
	sbuild := &Test2SchemaSelect{Test2SchemaQuery: tq}
	sbuild.label = test2schema.Label
	sbuild.flds, sbuild.scan = &tq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a Test2SchemaSelect configured with the given aggregations.
func (tq *Test2SchemaQuery) Aggregate(fns ...AggregateFunc) *Test2SchemaSelect {
	return tq.Select().Aggregate(fns...)
}

func (tq *Test2SchemaQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tq); err != nil {
				return err
			}
		}
	}
	for _, f := range tq.ctx.Fields {
		if !test2schema.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tq.path != nil {
		prev, err := tq.path(ctx)
		if err != nil {
			return err
		}
		tq.sql = prev
	}
	return nil
}

func (tq *Test2SchemaQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Test2Schema, error) {
	var (
		nodes = []*Test2Schema{}
		_spec = tq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Test2Schema).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Test2Schema{config: tq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (tq *Test2SchemaQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tq.querySpec()
	_spec.Node.Columns = tq.ctx.Fields
	if len(tq.ctx.Fields) > 0 {
		_spec.Unique = tq.ctx.Unique != nil && *tq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tq.driver, _spec)
}

func (tq *Test2SchemaQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(test2schema.Table, test2schema.Columns, sqlgraph.NewFieldSpec(test2schema.FieldID, field.TypeInt))
	_spec.From = tq.sql
	if unique := tq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tq.path != nil {
		_spec.Unique = true
	}
	if fields := tq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, test2schema.FieldID)
		for i := range fields {
			if fields[i] != test2schema.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tq *Test2SchemaQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tq.driver.Dialect())
	t1 := builder.Table(test2schema.Table)
	columns := tq.ctx.Fields
	if len(columns) == 0 {
		columns = test2schema.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tq.sql != nil {
		selector = tq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tq.ctx.Unique != nil && *tq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range tq.predicates {
		p(selector)
	}
	for _, p := range tq.order {
		p(selector)
	}
	if offset := tq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Test2SchemaGroupBy is the group-by builder for Test2Schema entities.
type Test2SchemaGroupBy struct {
	selector
	build *Test2SchemaQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tgb *Test2SchemaGroupBy) Aggregate(fns ...AggregateFunc) *Test2SchemaGroupBy {
	tgb.fns = append(tgb.fns, fns...)
	return tgb
}

// Scan applies the selector query and scans the result into the given value.
func (tgb *Test2SchemaGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tgb.build.ctx, ent.OpQueryGroupBy)
	if err := tgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*Test2SchemaQuery, *Test2SchemaGroupBy](ctx, tgb.build, tgb, tgb.build.inters, v)
}

func (tgb *Test2SchemaGroupBy) sqlScan(ctx context.Context, root *Test2SchemaQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tgb.fns))
	for _, fn := range tgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tgb.flds)+len(tgb.fns))
		for _, f := range *tgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Test2SchemaSelect is the builder for selecting fields of Test2Schema entities.
type Test2SchemaSelect struct {
	*Test2SchemaQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ts *Test2SchemaSelect) Aggregate(fns ...AggregateFunc) *Test2SchemaSelect {
	ts.fns = append(ts.fns, fns...)
	return ts
}

// Scan applies the selector query and scans the result into the given value.
func (ts *Test2SchemaSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ts.ctx, ent.OpQuerySelect)
	if err := ts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*Test2SchemaQuery, *Test2SchemaSelect](ctx, ts.Test2SchemaQuery, ts, ts.inters, v)
}

func (ts *Test2SchemaSelect) sqlScan(ctx context.Context, root *Test2SchemaQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ts.fns))
	for _, fn := range ts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
