// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"transaction-filter-backend/ent/test1schema"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Test1Schema is the model entity for the Test1Schema schema.
type Test1Schema struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// FieldString holds the value of the "field_string" field.
	FieldString string `json:"field_string,omitempty"`
	// FieldInt holds the value of the "field_int" field.
	FieldInt int `json:"field_int,omitempty"`
	// FieldFloat holds the value of the "field_float" field.
	FieldFloat float64 `json:"field_float,omitempty"`
	// FieldBool holds the value of the "field_bool" field.
	FieldBool bool `json:"field_bool,omitempty"`
	// FieldTime holds the value of the "field_time" field.
	FieldTime time.Time `json:"field_time,omitempty"`
	// FieldText holds the value of the "field_text" field.
	FieldText    string `json:"field_text,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Test1Schema) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case test1schema.FieldFieldBool:
			values[i] = new(sql.NullBool)
		case test1schema.FieldFieldFloat:
			values[i] = new(sql.NullFloat64)
		case test1schema.FieldID, test1schema.FieldFieldInt:
			values[i] = new(sql.NullInt64)
		case test1schema.FieldFieldString, test1schema.FieldFieldText:
			values[i] = new(sql.NullString)
		case test1schema.FieldFieldTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Test1Schema fields.
func (t *Test1Schema) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case test1schema.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			t.ID = int(value.Int64)
		case test1schema.FieldFieldString:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field field_string", values[i])
			} else if value.Valid {
				t.FieldString = value.String
			}
		case test1schema.FieldFieldInt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field field_int", values[i])
			} else if value.Valid {
				t.FieldInt = int(value.Int64)
			}
		case test1schema.FieldFieldFloat:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field field_float", values[i])
			} else if value.Valid {
				t.FieldFloat = value.Float64
			}
		case test1schema.FieldFieldBool:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field field_bool", values[i])
			} else if value.Valid {
				t.FieldBool = value.Bool
			}
		case test1schema.FieldFieldTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field field_time", values[i])
			} else if value.Valid {
				t.FieldTime = value.Time
			}
		case test1schema.FieldFieldText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field field_text", values[i])
			} else if value.Valid {
				t.FieldText = value.String
			}
		default:
			t.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Test1Schema.
// This includes values selected through modifiers, order, etc.
func (t *Test1Schema) Value(name string) (ent.Value, error) {
	return t.selectValues.Get(name)
}

// Update returns a builder for updating this Test1Schema.
// Note that you need to call Test1Schema.Unwrap() before calling this method if this Test1Schema
// was returned from a transaction, and the transaction was committed or rolled back.
func (t *Test1Schema) Update() *Test1SchemaUpdateOne {
	return NewTest1SchemaClient(t.config).UpdateOne(t)
}

// Unwrap unwraps the Test1Schema entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (t *Test1Schema) Unwrap() *Test1Schema {
	_tx, ok := t.config.driver.(*txDriver)
	if !ok {
		panic("ent: Test1Schema is not a transactional entity")
	}
	t.config.driver = _tx.drv
	return t
}

// String implements the fmt.Stringer.
func (t *Test1Schema) String() string {
	var builder strings.Builder
	builder.WriteString("Test1Schema(")
	builder.WriteString(fmt.Sprintf("id=%v, ", t.ID))
	builder.WriteString("field_string=")
	builder.WriteString(t.FieldString)
	builder.WriteString(", ")
	builder.WriteString("field_int=")
	builder.WriteString(fmt.Sprintf("%v", t.FieldInt))
	builder.WriteString(", ")
	builder.WriteString("field_float=")
	builder.WriteString(fmt.Sprintf("%v", t.FieldFloat))
	builder.WriteString(", ")
	builder.WriteString("field_bool=")
	builder.WriteString(fmt.Sprintf("%v", t.FieldBool))
	builder.WriteString(", ")
	builder.WriteString("field_time=")
	builder.WriteString(t.FieldTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("field_text=")
	builder.WriteString(t.FieldText)
	builder.WriteByte(')')
	return builder.String()
}

// Test1Schemas is a parsable slice of Test1Schema.
type Test1Schemas []*Test1Schema
