// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"transaction-filter-backend/ent/predicate"
	"transaction-filter-backend/ent/test2schema"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// Test2SchemaUpdate is the builder for updating Test2Schema entities.
type Test2SchemaUpdate struct {
	config
	hooks    []Hook
	mutation *Test2SchemaMutation
}

// Where appends a list predicates to the Test2SchemaUpdate builder.
func (tu *Test2SchemaUpdate) Where(ps ...predicate.Test2Schema) *Test2SchemaUpdate {
	tu.mutation.Where(ps...)
	return tu
}

// SetName sets the "name" field.
func (tu *Test2SchemaUpdate) SetName(s string) *Test2SchemaUpdate {
	tu.mutation.SetName(s)
	return tu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (tu *Test2SchemaUpdate) SetNillableName(s *string) *Test2SchemaUpdate {
	if s != nil {
		tu.SetName(*s)
	}
	return tu
}

// SetDescription sets the "description" field.
func (tu *Test2SchemaUpdate) SetDescription(s string) *Test2SchemaUpdate {
	tu.mutation.SetDescription(s)
	return tu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (tu *Test2SchemaUpdate) SetNillableDescription(s *string) *Test2SchemaUpdate {
	if s != nil {
		tu.SetDescription(*s)
	}
	return tu
}

// ClearDescription clears the value of the "description" field.
func (tu *Test2SchemaUpdate) ClearDescription() *Test2SchemaUpdate {
	tu.mutation.ClearDescription()
	return tu
}

// SetQuantity sets the "quantity" field.
func (tu *Test2SchemaUpdate) SetQuantity(i int) *Test2SchemaUpdate {
	tu.mutation.ResetQuantity()
	tu.mutation.SetQuantity(i)
	return tu
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (tu *Test2SchemaUpdate) SetNillableQuantity(i *int) *Test2SchemaUpdate {
	if i != nil {
		tu.SetQuantity(*i)
	}
	return tu
}

// AddQuantity adds i to the "quantity" field.
func (tu *Test2SchemaUpdate) AddQuantity(i int) *Test2SchemaUpdate {
	tu.mutation.AddQuantity(i)
	return tu
}

// SetPrice sets the "price" field.
func (tu *Test2SchemaUpdate) SetPrice(f float64) *Test2SchemaUpdate {
	tu.mutation.ResetPrice()
	tu.mutation.SetPrice(f)
	return tu
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (tu *Test2SchemaUpdate) SetNillablePrice(f *float64) *Test2SchemaUpdate {
	if f != nil {
		tu.SetPrice(*f)
	}
	return tu
}

// AddPrice adds f to the "price" field.
func (tu *Test2SchemaUpdate) AddPrice(f float64) *Test2SchemaUpdate {
	tu.mutation.AddPrice(f)
	return tu
}

// SetActive sets the "active" field.
func (tu *Test2SchemaUpdate) SetActive(b bool) *Test2SchemaUpdate {
	tu.mutation.SetActive(b)
	return tu
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (tu *Test2SchemaUpdate) SetNillableActive(b *bool) *Test2SchemaUpdate {
	if b != nil {
		tu.SetActive(*b)
	}
	return tu
}

// SetCreatedAt sets the "created_at" field.
func (tu *Test2SchemaUpdate) SetCreatedAt(t time.Time) *Test2SchemaUpdate {
	tu.mutation.SetCreatedAt(t)
	return tu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tu *Test2SchemaUpdate) SetNillableCreatedAt(t *time.Time) *Test2SchemaUpdate {
	if t != nil {
		tu.SetCreatedAt(*t)
	}
	return tu
}

// SetUpdatedAt sets the "updated_at" field.
func (tu *Test2SchemaUpdate) SetUpdatedAt(t time.Time) *Test2SchemaUpdate {
	tu.mutation.SetUpdatedAt(t)
	return tu
}

// SetItemType sets the "item_type" field.
func (tu *Test2SchemaUpdate) SetItemType(s string) *Test2SchemaUpdate {
	tu.mutation.SetItemType(s)
	return tu
}

// SetNillableItemType sets the "item_type" field if the given value is not nil.
func (tu *Test2SchemaUpdate) SetNillableItemType(s *string) *Test2SchemaUpdate {
	if s != nil {
		tu.SetItemType(*s)
	}
	return tu
}

// ClearItemType clears the value of the "item_type" field.
func (tu *Test2SchemaUpdate) ClearItemType() *Test2SchemaUpdate {
	tu.mutation.ClearItemType()
	return tu
}

// Mutation returns the Test2SchemaMutation object of the builder.
func (tu *Test2SchemaUpdate) Mutation() *Test2SchemaMutation {
	return tu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tu *Test2SchemaUpdate) Save(ctx context.Context) (int, error) {
	tu.defaults()
	return withHooks(ctx, tu.sqlSave, tu.mutation, tu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tu *Test2SchemaUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *Test2SchemaUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *Test2SchemaUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tu *Test2SchemaUpdate) defaults() {
	if _, ok := tu.mutation.UpdatedAt(); !ok {
		v := test2schema.UpdateDefaultUpdatedAt()
		tu.mutation.SetUpdatedAt(v)
	}
}

func (tu *Test2SchemaUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(test2schema.Table, test2schema.Columns, sqlgraph.NewFieldSpec(test2schema.FieldID, field.TypeInt))
	if ps := tu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.Name(); ok {
		_spec.SetField(test2schema.FieldName, field.TypeString, value)
	}
	if value, ok := tu.mutation.Description(); ok {
		_spec.SetField(test2schema.FieldDescription, field.TypeString, value)
	}
	if tu.mutation.DescriptionCleared() {
		_spec.ClearField(test2schema.FieldDescription, field.TypeString)
	}
	if value, ok := tu.mutation.Quantity(); ok {
		_spec.SetField(test2schema.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := tu.mutation.AddedQuantity(); ok {
		_spec.AddField(test2schema.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := tu.mutation.Price(); ok {
		_spec.SetField(test2schema.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := tu.mutation.AddedPrice(); ok {
		_spec.AddField(test2schema.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := tu.mutation.Active(); ok {
		_spec.SetField(test2schema.FieldActive, field.TypeBool, value)
	}
	if value, ok := tu.mutation.CreatedAt(); ok {
		_spec.SetField(test2schema.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := tu.mutation.UpdatedAt(); ok {
		_spec.SetField(test2schema.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := tu.mutation.ItemType(); ok {
		_spec.SetField(test2schema.FieldItemType, field.TypeString, value)
	}
	if tu.mutation.ItemTypeCleared() {
		_spec.ClearField(test2schema.FieldItemType, field.TypeString)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{test2schema.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tu.mutation.done = true
	return n, nil
}

// Test2SchemaUpdateOne is the builder for updating a single Test2Schema entity.
type Test2SchemaUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *Test2SchemaMutation
}

// SetName sets the "name" field.
func (tuo *Test2SchemaUpdateOne) SetName(s string) *Test2SchemaUpdateOne {
	tuo.mutation.SetName(s)
	return tuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (tuo *Test2SchemaUpdateOne) SetNillableName(s *string) *Test2SchemaUpdateOne {
	if s != nil {
		tuo.SetName(*s)
	}
	return tuo
}

// SetDescription sets the "description" field.
func (tuo *Test2SchemaUpdateOne) SetDescription(s string) *Test2SchemaUpdateOne {
	tuo.mutation.SetDescription(s)
	return tuo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (tuo *Test2SchemaUpdateOne) SetNillableDescription(s *string) *Test2SchemaUpdateOne {
	if s != nil {
		tuo.SetDescription(*s)
	}
	return tuo
}

// ClearDescription clears the value of the "description" field.
func (tuo *Test2SchemaUpdateOne) ClearDescription() *Test2SchemaUpdateOne {
	tuo.mutation.ClearDescription()
	return tuo
}

// SetQuantity sets the "quantity" field.
func (tuo *Test2SchemaUpdateOne) SetQuantity(i int) *Test2SchemaUpdateOne {
	tuo.mutation.ResetQuantity()
	tuo.mutation.SetQuantity(i)
	return tuo
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (tuo *Test2SchemaUpdateOne) SetNillableQuantity(i *int) *Test2SchemaUpdateOne {
	if i != nil {
		tuo.SetQuantity(*i)
	}
	return tuo
}

// AddQuantity adds i to the "quantity" field.
func (tuo *Test2SchemaUpdateOne) AddQuantity(i int) *Test2SchemaUpdateOne {
	tuo.mutation.AddQuantity(i)
	return tuo
}

// SetPrice sets the "price" field.
func (tuo *Test2SchemaUpdateOne) SetPrice(f float64) *Test2SchemaUpdateOne {
	tuo.mutation.ResetPrice()
	tuo.mutation.SetPrice(f)
	return tuo
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (tuo *Test2SchemaUpdateOne) SetNillablePrice(f *float64) *Test2SchemaUpdateOne {
	if f != nil {
		tuo.SetPrice(*f)
	}
	return tuo
}

// AddPrice adds f to the "price" field.
func (tuo *Test2SchemaUpdateOne) AddPrice(f float64) *Test2SchemaUpdateOne {
	tuo.mutation.AddPrice(f)
	return tuo
}

// SetActive sets the "active" field.
func (tuo *Test2SchemaUpdateOne) SetActive(b bool) *Test2SchemaUpdateOne {
	tuo.mutation.SetActive(b)
	return tuo
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (tuo *Test2SchemaUpdateOne) SetNillableActive(b *bool) *Test2SchemaUpdateOne {
	if b != nil {
		tuo.SetActive(*b)
	}
	return tuo
}

// SetCreatedAt sets the "created_at" field.
func (tuo *Test2SchemaUpdateOne) SetCreatedAt(t time.Time) *Test2SchemaUpdateOne {
	tuo.mutation.SetCreatedAt(t)
	return tuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tuo *Test2SchemaUpdateOne) SetNillableCreatedAt(t *time.Time) *Test2SchemaUpdateOne {
	if t != nil {
		tuo.SetCreatedAt(*t)
	}
	return tuo
}

// SetUpdatedAt sets the "updated_at" field.
func (tuo *Test2SchemaUpdateOne) SetUpdatedAt(t time.Time) *Test2SchemaUpdateOne {
	tuo.mutation.SetUpdatedAt(t)
	return tuo
}

// SetItemType sets the "item_type" field.
func (tuo *Test2SchemaUpdateOne) SetItemType(s string) *Test2SchemaUpdateOne {
	tuo.mutation.SetItemType(s)
	return tuo
}

// SetNillableItemType sets the "item_type" field if the given value is not nil.
func (tuo *Test2SchemaUpdateOne) SetNillableItemType(s *string) *Test2SchemaUpdateOne {
	if s != nil {
		tuo.SetItemType(*s)
	}
	return tuo
}

// ClearItemType clears the value of the "item_type" field.
func (tuo *Test2SchemaUpdateOne) ClearItemType() *Test2SchemaUpdateOne {
	tuo.mutation.ClearItemType()
	return tuo
}

// Mutation returns the Test2SchemaMutation object of the builder.
func (tuo *Test2SchemaUpdateOne) Mutation() *Test2SchemaMutation {
	return tuo.mutation
}

// Where appends a list predicates to the Test2SchemaUpdate builder.
func (tuo *Test2SchemaUpdateOne) Where(ps ...predicate.Test2Schema) *Test2SchemaUpdateOne {
	tuo.mutation.Where(ps...)
	return tuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tuo *Test2SchemaUpdateOne) Select(field string, fields ...string) *Test2SchemaUpdateOne {
	tuo.fields = append([]string{field}, fields...)
	return tuo
}

// Save executes the query and returns the updated Test2Schema entity.
func (tuo *Test2SchemaUpdateOne) Save(ctx context.Context) (*Test2Schema, error) {
	tuo.defaults()
	return withHooks(ctx, tuo.sqlSave, tuo.mutation, tuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *Test2SchemaUpdateOne) SaveX(ctx context.Context) *Test2Schema {
	node, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tuo *Test2SchemaUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *Test2SchemaUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tuo *Test2SchemaUpdateOne) defaults() {
	if _, ok := tuo.mutation.UpdatedAt(); !ok {
		v := test2schema.UpdateDefaultUpdatedAt()
		tuo.mutation.SetUpdatedAt(v)
	}
}

func (tuo *Test2SchemaUpdateOne) sqlSave(ctx context.Context) (_node *Test2Schema, err error) {
	_spec := sqlgraph.NewUpdateSpec(test2schema.Table, test2schema.Columns, sqlgraph.NewFieldSpec(test2schema.FieldID, field.TypeInt))
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Test2Schema.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, test2schema.FieldID)
		for _, f := range fields {
			if !test2schema.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != test2schema.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuo.mutation.Name(); ok {
		_spec.SetField(test2schema.FieldName, field.TypeString, value)
	}
	if value, ok := tuo.mutation.Description(); ok {
		_spec.SetField(test2schema.FieldDescription, field.TypeString, value)
	}
	if tuo.mutation.DescriptionCleared() {
		_spec.ClearField(test2schema.FieldDescription, field.TypeString)
	}
	if value, ok := tuo.mutation.Quantity(); ok {
		_spec.SetField(test2schema.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.AddedQuantity(); ok {
		_spec.AddField(test2schema.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.Price(); ok {
		_spec.SetField(test2schema.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := tuo.mutation.AddedPrice(); ok {
		_spec.AddField(test2schema.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := tuo.mutation.Active(); ok {
		_spec.SetField(test2schema.FieldActive, field.TypeBool, value)
	}
	if value, ok := tuo.mutation.CreatedAt(); ok {
		_spec.SetField(test2schema.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := tuo.mutation.UpdatedAt(); ok {
		_spec.SetField(test2schema.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := tuo.mutation.ItemType(); ok {
		_spec.SetField(test2schema.FieldItemType, field.TypeString, value)
	}
	if tuo.mutation.ItemTypeCleared() {
		_spec.ClearField(test2schema.FieldItemType, field.TypeString)
	}
	_node = &Test2Schema{config: tuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{test2schema.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tuo.mutation.done = true
	return _node, nil
}
