// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"transaction-filter-backend/ent/predicate"
	"transaction-filter-backend/ent/test3schema"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// Test3SchemaUpdate is the builder for updating Test3Schema entities.
type Test3SchemaUpdate struct {
	config
	hooks    []Hook
	mutation *Test3SchemaMutation
}

// Where appends a list predicates to the Test3SchemaUpdate builder.
func (tu *Test3SchemaUpdate) Where(ps ...predicate.Test3Schema) *Test3SchemaUpdate {
	tu.mutation.Where(ps...)
	return tu
}

// SetSku sets the "sku" field.
func (tu *Test3SchemaUpdate) SetSku(s string) *Test3SchemaUpdate {
	tu.mutation.SetSku(s)
	return tu
}

// SetNillableSku sets the "sku" field if the given value is not nil.
func (tu *Test3SchemaUpdate) SetNillableSku(s *string) *Test3SchemaUpdate {
	if s != nil {
		tu.SetSku(*s)
	}
	return tu
}

// SetProductName sets the "product_name" field.
func (tu *Test3SchemaUpdate) SetProductName(s string) *Test3SchemaUpdate {
	tu.mutation.SetProductName(s)
	return tu
}

// SetNillableProductName sets the "product_name" field if the given value is not nil.
func (tu *Test3SchemaUpdate) SetNillableProductName(s *string) *Test3SchemaUpdate {
	if s != nil {
		tu.SetProductName(*s)
	}
	return tu
}

// SetShortDescription sets the "short_description" field.
func (tu *Test3SchemaUpdate) SetShortDescription(s string) *Test3SchemaUpdate {
	tu.mutation.SetShortDescription(s)
	return tu
}

// SetNillableShortDescription sets the "short_description" field if the given value is not nil.
func (tu *Test3SchemaUpdate) SetNillableShortDescription(s *string) *Test3SchemaUpdate {
	if s != nil {
		tu.SetShortDescription(*s)
	}
	return tu
}

// ClearShortDescription clears the value of the "short_description" field.
func (tu *Test3SchemaUpdate) ClearShortDescription() *Test3SchemaUpdate {
	tu.mutation.ClearShortDescription()
	return tu
}

// SetFullDescription sets the "full_description" field.
func (tu *Test3SchemaUpdate) SetFullDescription(s string) *Test3SchemaUpdate {
	tu.mutation.SetFullDescription(s)
	return tu
}

// SetNillableFullDescription sets the "full_description" field if the given value is not nil.
func (tu *Test3SchemaUpdate) SetNillableFullDescription(s *string) *Test3SchemaUpdate {
	if s != nil {
		tu.SetFullDescription(*s)
	}
	return tu
}

// ClearFullDescription clears the value of the "full_description" field.
func (tu *Test3SchemaUpdate) ClearFullDescription() *Test3SchemaUpdate {
	tu.mutation.ClearFullDescription()
	return tu
}

// SetCostPrice sets the "cost_price" field.
func (tu *Test3SchemaUpdate) SetCostPrice(f float64) *Test3SchemaUpdate {
	tu.mutation.ResetCostPrice()
	tu.mutation.SetCostPrice(f)
	return tu
}

// SetNillableCostPrice sets the "cost_price" field if the given value is not nil.
func (tu *Test3SchemaUpdate) SetNillableCostPrice(f *float64) *Test3SchemaUpdate {
	if f != nil {
		tu.SetCostPrice(*f)
	}
	return tu
}

// AddCostPrice adds f to the "cost_price" field.
func (tu *Test3SchemaUpdate) AddCostPrice(f float64) *Test3SchemaUpdate {
	tu.mutation.AddCostPrice(f)
	return tu
}

// SetRetailPrice sets the "retail_price" field.
func (tu *Test3SchemaUpdate) SetRetailPrice(f float64) *Test3SchemaUpdate {
	tu.mutation.ResetRetailPrice()
	tu.mutation.SetRetailPrice(f)
	return tu
}

// SetNillableRetailPrice sets the "retail_price" field if the given value is not nil.
func (tu *Test3SchemaUpdate) SetNillableRetailPrice(f *float64) *Test3SchemaUpdate {
	if f != nil {
		tu.SetRetailPrice(*f)
	}
	return tu
}

// AddRetailPrice adds f to the "retail_price" field.
func (tu *Test3SchemaUpdate) AddRetailPrice(f float64) *Test3SchemaUpdate {
	tu.mutation.AddRetailPrice(f)
	return tu
}

// SetStockCount sets the "stock_count" field.
func (tu *Test3SchemaUpdate) SetStockCount(i int) *Test3SchemaUpdate {
	tu.mutation.ResetStockCount()
	tu.mutation.SetStockCount(i)
	return tu
}

// SetNillableStockCount sets the "stock_count" field if the given value is not nil.
func (tu *Test3SchemaUpdate) SetNillableStockCount(i *int) *Test3SchemaUpdate {
	if i != nil {
		tu.SetStockCount(*i)
	}
	return tu
}

// AddStockCount adds i to the "stock_count" field.
func (tu *Test3SchemaUpdate) AddStockCount(i int) *Test3SchemaUpdate {
	tu.mutation.AddStockCount(i)
	return tu
}

// SetIsActive sets the "is_active" field.
func (tu *Test3SchemaUpdate) SetIsActive(b bool) *Test3SchemaUpdate {
	tu.mutation.SetIsActive(b)
	return tu
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (tu *Test3SchemaUpdate) SetNillableIsActive(b *bool) *Test3SchemaUpdate {
	if b != nil {
		tu.SetIsActive(*b)
	}
	return tu
}

// SetPublishedAt sets the "published_at" field.
func (tu *Test3SchemaUpdate) SetPublishedAt(t time.Time) *Test3SchemaUpdate {
	tu.mutation.SetPublishedAt(t)
	return tu
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (tu *Test3SchemaUpdate) SetNillablePublishedAt(t *time.Time) *Test3SchemaUpdate {
	if t != nil {
		tu.SetPublishedAt(*t)
	}
	return tu
}

// ClearPublishedAt clears the value of the "published_at" field.
func (tu *Test3SchemaUpdate) ClearPublishedAt() *Test3SchemaUpdate {
	tu.mutation.ClearPublishedAt()
	return tu
}

// SetLastOrderedAt sets the "last_ordered_at" field.
func (tu *Test3SchemaUpdate) SetLastOrderedAt(t time.Time) *Test3SchemaUpdate {
	tu.mutation.SetLastOrderedAt(t)
	return tu
}

// SetNillableLastOrderedAt sets the "last_ordered_at" field if the given value is not nil.
func (tu *Test3SchemaUpdate) SetNillableLastOrderedAt(t *time.Time) *Test3SchemaUpdate {
	if t != nil {
		tu.SetLastOrderedAt(*t)
	}
	return tu
}

// ClearLastOrderedAt clears the value of the "last_ordered_at" field.
func (tu *Test3SchemaUpdate) ClearLastOrderedAt() *Test3SchemaUpdate {
	tu.mutation.ClearLastOrderedAt()
	return tu
}

// SetTags sets the "tags" field.
func (tu *Test3SchemaUpdate) SetTags(s string) *Test3SchemaUpdate {
	tu.mutation.SetTags(s)
	return tu
}

// SetNillableTags sets the "tags" field if the given value is not nil.
func (tu *Test3SchemaUpdate) SetNillableTags(s *string) *Test3SchemaUpdate {
	if s != nil {
		tu.SetTags(*s)
	}
	return tu
}

// ClearTags clears the value of the "tags" field.
func (tu *Test3SchemaUpdate) ClearTags() *Test3SchemaUpdate {
	tu.mutation.ClearTags()
	return tu
}

// Mutation returns the Test3SchemaMutation object of the builder.
func (tu *Test3SchemaUpdate) Mutation() *Test3SchemaMutation {
	return tu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tu *Test3SchemaUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, tu.sqlSave, tu.mutation, tu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tu *Test3SchemaUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *Test3SchemaUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *Test3SchemaUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tu *Test3SchemaUpdate) check() error {
	if v, ok := tu.mutation.Sku(); ok {
		if err := test3schema.SkuValidator(v); err != nil {
			return &ValidationError{Name: "sku", err: fmt.Errorf(`ent: validator failed for field "Test3Schema.sku": %w`, err)}
		}
	}
	return nil
}

func (tu *Test3SchemaUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := tu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(test3schema.Table, test3schema.Columns, sqlgraph.NewFieldSpec(test3schema.FieldID, field.TypeInt))
	if ps := tu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.Sku(); ok {
		_spec.SetField(test3schema.FieldSku, field.TypeString, value)
	}
	if value, ok := tu.mutation.ProductName(); ok {
		_spec.SetField(test3schema.FieldProductName, field.TypeString, value)
	}
	if value, ok := tu.mutation.ShortDescription(); ok {
		_spec.SetField(test3schema.FieldShortDescription, field.TypeString, value)
	}
	if tu.mutation.ShortDescriptionCleared() {
		_spec.ClearField(test3schema.FieldShortDescription, field.TypeString)
	}
	if value, ok := tu.mutation.FullDescription(); ok {
		_spec.SetField(test3schema.FieldFullDescription, field.TypeString, value)
	}
	if tu.mutation.FullDescriptionCleared() {
		_spec.ClearField(test3schema.FieldFullDescription, field.TypeString)
	}
	if value, ok := tu.mutation.CostPrice(); ok {
		_spec.SetField(test3schema.FieldCostPrice, field.TypeFloat64, value)
	}
	if value, ok := tu.mutation.AddedCostPrice(); ok {
		_spec.AddField(test3schema.FieldCostPrice, field.TypeFloat64, value)
	}
	if value, ok := tu.mutation.RetailPrice(); ok {
		_spec.SetField(test3schema.FieldRetailPrice, field.TypeFloat64, value)
	}
	if value, ok := tu.mutation.AddedRetailPrice(); ok {
		_spec.AddField(test3schema.FieldRetailPrice, field.TypeFloat64, value)
	}
	if value, ok := tu.mutation.StockCount(); ok {
		_spec.SetField(test3schema.FieldStockCount, field.TypeInt, value)
	}
	if value, ok := tu.mutation.AddedStockCount(); ok {
		_spec.AddField(test3schema.FieldStockCount, field.TypeInt, value)
	}
	if value, ok := tu.mutation.IsActive(); ok {
		_spec.SetField(test3schema.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := tu.mutation.PublishedAt(); ok {
		_spec.SetField(test3schema.FieldPublishedAt, field.TypeTime, value)
	}
	if tu.mutation.PublishedAtCleared() {
		_spec.ClearField(test3schema.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := tu.mutation.LastOrderedAt(); ok {
		_spec.SetField(test3schema.FieldLastOrderedAt, field.TypeTime, value)
	}
	if tu.mutation.LastOrderedAtCleared() {
		_spec.ClearField(test3schema.FieldLastOrderedAt, field.TypeTime)
	}
	if value, ok := tu.mutation.Tags(); ok {
		_spec.SetField(test3schema.FieldTags, field.TypeString, value)
	}
	if tu.mutation.TagsCleared() {
		_spec.ClearField(test3schema.FieldTags, field.TypeString)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{test3schema.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tu.mutation.done = true
	return n, nil
}

// Test3SchemaUpdateOne is the builder for updating a single Test3Schema entity.
type Test3SchemaUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *Test3SchemaMutation
}

// SetSku sets the "sku" field.
func (tuo *Test3SchemaUpdateOne) SetSku(s string) *Test3SchemaUpdateOne {
	tuo.mutation.SetSku(s)
	return tuo
}

// SetNillableSku sets the "sku" field if the given value is not nil.
func (tuo *Test3SchemaUpdateOne) SetNillableSku(s *string) *Test3SchemaUpdateOne {
	if s != nil {
		tuo.SetSku(*s)
	}
	return tuo
}

// SetProductName sets the "product_name" field.
func (tuo *Test3SchemaUpdateOne) SetProductName(s string) *Test3SchemaUpdateOne {
	tuo.mutation.SetProductName(s)
	return tuo
}

// SetNillableProductName sets the "product_name" field if the given value is not nil.
func (tuo *Test3SchemaUpdateOne) SetNillableProductName(s *string) *Test3SchemaUpdateOne {
	if s != nil {
		tuo.SetProductName(*s)
	}
	return tuo
}

// SetShortDescription sets the "short_description" field.
func (tuo *Test3SchemaUpdateOne) SetShortDescription(s string) *Test3SchemaUpdateOne {
	tuo.mutation.SetShortDescription(s)
	return tuo
}

// SetNillableShortDescription sets the "short_description" field if the given value is not nil.
func (tuo *Test3SchemaUpdateOne) SetNillableShortDescription(s *string) *Test3SchemaUpdateOne {
	if s != nil {
		tuo.SetShortDescription(*s)
	}
	return tuo
}

// ClearShortDescription clears the value of the "short_description" field.
func (tuo *Test3SchemaUpdateOne) ClearShortDescription() *Test3SchemaUpdateOne {
	tuo.mutation.ClearShortDescription()
	return tuo
}

// SetFullDescription sets the "full_description" field.
func (tuo *Test3SchemaUpdateOne) SetFullDescription(s string) *Test3SchemaUpdateOne {
	tuo.mutation.SetFullDescription(s)
	return tuo
}

// SetNillableFullDescription sets the "full_description" field if the given value is not nil.
func (tuo *Test3SchemaUpdateOne) SetNillableFullDescription(s *string) *Test3SchemaUpdateOne {
	if s != nil {
		tuo.SetFullDescription(*s)
	}
	return tuo
}

// ClearFullDescription clears the value of the "full_description" field.
func (tuo *Test3SchemaUpdateOne) ClearFullDescription() *Test3SchemaUpdateOne {
	tuo.mutation.ClearFullDescription()
	return tuo
}

// SetCostPrice sets the "cost_price" field.
func (tuo *Test3SchemaUpdateOne) SetCostPrice(f float64) *Test3SchemaUpdateOne {
	tuo.mutation.ResetCostPrice()
	tuo.mutation.SetCostPrice(f)
	return tuo
}

// SetNillableCostPrice sets the "cost_price" field if the given value is not nil.
func (tuo *Test3SchemaUpdateOne) SetNillableCostPrice(f *float64) *Test3SchemaUpdateOne {
	if f != nil {
		tuo.SetCostPrice(*f)
	}
	return tuo
}

// AddCostPrice adds f to the "cost_price" field.
func (tuo *Test3SchemaUpdateOne) AddCostPrice(f float64) *Test3SchemaUpdateOne {
	tuo.mutation.AddCostPrice(f)
	return tuo
}

// SetRetailPrice sets the "retail_price" field.
func (tuo *Test3SchemaUpdateOne) SetRetailPrice(f float64) *Test3SchemaUpdateOne {
	tuo.mutation.ResetRetailPrice()
	tuo.mutation.SetRetailPrice(f)
	return tuo
}

// SetNillableRetailPrice sets the "retail_price" field if the given value is not nil.
func (tuo *Test3SchemaUpdateOne) SetNillableRetailPrice(f *float64) *Test3SchemaUpdateOne {
	if f != nil {
		tuo.SetRetailPrice(*f)
	}
	return tuo
}

// AddRetailPrice adds f to the "retail_price" field.
func (tuo *Test3SchemaUpdateOne) AddRetailPrice(f float64) *Test3SchemaUpdateOne {
	tuo.mutation.AddRetailPrice(f)
	return tuo
}

// SetStockCount sets the "stock_count" field.
func (tuo *Test3SchemaUpdateOne) SetStockCount(i int) *Test3SchemaUpdateOne {
	tuo.mutation.ResetStockCount()
	tuo.mutation.SetStockCount(i)
	return tuo
}

// SetNillableStockCount sets the "stock_count" field if the given value is not nil.
func (tuo *Test3SchemaUpdateOne) SetNillableStockCount(i *int) *Test3SchemaUpdateOne {
	if i != nil {
		tuo.SetStockCount(*i)
	}
	return tuo
}

// AddStockCount adds i to the "stock_count" field.
func (tuo *Test3SchemaUpdateOne) AddStockCount(i int) *Test3SchemaUpdateOne {
	tuo.mutation.AddStockCount(i)
	return tuo
}

// SetIsActive sets the "is_active" field.
func (tuo *Test3SchemaUpdateOne) SetIsActive(b bool) *Test3SchemaUpdateOne {
	tuo.mutation.SetIsActive(b)
	return tuo
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (tuo *Test3SchemaUpdateOne) SetNillableIsActive(b *bool) *Test3SchemaUpdateOne {
	if b != nil {
		tuo.SetIsActive(*b)
	}
	return tuo
}

// SetPublishedAt sets the "published_at" field.
func (tuo *Test3SchemaUpdateOne) SetPublishedAt(t time.Time) *Test3SchemaUpdateOne {
	tuo.mutation.SetPublishedAt(t)
	return tuo
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (tuo *Test3SchemaUpdateOne) SetNillablePublishedAt(t *time.Time) *Test3SchemaUpdateOne {
	if t != nil {
		tuo.SetPublishedAt(*t)
	}
	return tuo
}

// ClearPublishedAt clears the value of the "published_at" field.
func (tuo *Test3SchemaUpdateOne) ClearPublishedAt() *Test3SchemaUpdateOne {
	tuo.mutation.ClearPublishedAt()
	return tuo
}

// SetLastOrderedAt sets the "last_ordered_at" field.
func (tuo *Test3SchemaUpdateOne) SetLastOrderedAt(t time.Time) *Test3SchemaUpdateOne {
	tuo.mutation.SetLastOrderedAt(t)
	return tuo
}

// SetNillableLastOrderedAt sets the "last_ordered_at" field if the given value is not nil.
func (tuo *Test3SchemaUpdateOne) SetNillableLastOrderedAt(t *time.Time) *Test3SchemaUpdateOne {
	if t != nil {
		tuo.SetLastOrderedAt(*t)
	}
	return tuo
}

// ClearLastOrderedAt clears the value of the "last_ordered_at" field.
func (tuo *Test3SchemaUpdateOne) ClearLastOrderedAt() *Test3SchemaUpdateOne {
	tuo.mutation.ClearLastOrderedAt()
	return tuo
}

// SetTags sets the "tags" field.
func (tuo *Test3SchemaUpdateOne) SetTags(s string) *Test3SchemaUpdateOne {
	tuo.mutation.SetTags(s)
	return tuo
}

// SetNillableTags sets the "tags" field if the given value is not nil.
func (tuo *Test3SchemaUpdateOne) SetNillableTags(s *string) *Test3SchemaUpdateOne {
	if s != nil {
		tuo.SetTags(*s)
	}
	return tuo
}

// ClearTags clears the value of the "tags" field.
func (tuo *Test3SchemaUpdateOne) ClearTags() *Test3SchemaUpdateOne {
	tuo.mutation.ClearTags()
	return tuo
}

// Mutation returns the Test3SchemaMutation object of the builder.
func (tuo *Test3SchemaUpdateOne) Mutation() *Test3SchemaMutation {
	return tuo.mutation
}

// Where appends a list predicates to the Test3SchemaUpdate builder.
func (tuo *Test3SchemaUpdateOne) Where(ps ...predicate.Test3Schema) *Test3SchemaUpdateOne {
	tuo.mutation.Where(ps...)
	return tuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tuo *Test3SchemaUpdateOne) Select(field string, fields ...string) *Test3SchemaUpdateOne {
	tuo.fields = append([]string{field}, fields...)
	return tuo
}

// Save executes the query and returns the updated Test3Schema entity.
func (tuo *Test3SchemaUpdateOne) Save(ctx context.Context) (*Test3Schema, error) {
	return withHooks(ctx, tuo.sqlSave, tuo.mutation, tuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *Test3SchemaUpdateOne) SaveX(ctx context.Context) *Test3Schema {
	node, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tuo *Test3SchemaUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *Test3SchemaUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tuo *Test3SchemaUpdateOne) check() error {
	if v, ok := tuo.mutation.Sku(); ok {
		if err := test3schema.SkuValidator(v); err != nil {
			return &ValidationError{Name: "sku", err: fmt.Errorf(`ent: validator failed for field "Test3Schema.sku": %w`, err)}
		}
	}
	return nil
}

func (tuo *Test3SchemaUpdateOne) sqlSave(ctx context.Context) (_node *Test3Schema, err error) {
	if err := tuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(test3schema.Table, test3schema.Columns, sqlgraph.NewFieldSpec(test3schema.FieldID, field.TypeInt))
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Test3Schema.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, test3schema.FieldID)
		for _, f := range fields {
			if !test3schema.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != test3schema.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuo.mutation.Sku(); ok {
		_spec.SetField(test3schema.FieldSku, field.TypeString, value)
	}
	if value, ok := tuo.mutation.ProductName(); ok {
		_spec.SetField(test3schema.FieldProductName, field.TypeString, value)
	}
	if value, ok := tuo.mutation.ShortDescription(); ok {
		_spec.SetField(test3schema.FieldShortDescription, field.TypeString, value)
	}
	if tuo.mutation.ShortDescriptionCleared() {
		_spec.ClearField(test3schema.FieldShortDescription, field.TypeString)
	}
	if value, ok := tuo.mutation.FullDescription(); ok {
		_spec.SetField(test3schema.FieldFullDescription, field.TypeString, value)
	}
	if tuo.mutation.FullDescriptionCleared() {
		_spec.ClearField(test3schema.FieldFullDescription, field.TypeString)
	}
	if value, ok := tuo.mutation.CostPrice(); ok {
		_spec.SetField(test3schema.FieldCostPrice, field.TypeFloat64, value)
	}
	if value, ok := tuo.mutation.AddedCostPrice(); ok {
		_spec.AddField(test3schema.FieldCostPrice, field.TypeFloat64, value)
	}
	if value, ok := tuo.mutation.RetailPrice(); ok {
		_spec.SetField(test3schema.FieldRetailPrice, field.TypeFloat64, value)
	}
	if value, ok := tuo.mutation.AddedRetailPrice(); ok {
		_spec.AddField(test3schema.FieldRetailPrice, field.TypeFloat64, value)
	}
	if value, ok := tuo.mutation.StockCount(); ok {
		_spec.SetField(test3schema.FieldStockCount, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.AddedStockCount(); ok {
		_spec.AddField(test3schema.FieldStockCount, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.IsActive(); ok {
		_spec.SetField(test3schema.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := tuo.mutation.PublishedAt(); ok {
		_spec.SetField(test3schema.FieldPublishedAt, field.TypeTime, value)
	}
	if tuo.mutation.PublishedAtCleared() {
		_spec.ClearField(test3schema.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := tuo.mutation.LastOrderedAt(); ok {
		_spec.SetField(test3schema.FieldLastOrderedAt, field.TypeTime, value)
	}
	if tuo.mutation.LastOrderedAtCleared() {
		_spec.ClearField(test3schema.FieldLastOrderedAt, field.TypeTime)
	}
	if value, ok := tuo.mutation.Tags(); ok {
		_spec.SetField(test3schema.FieldTags, field.TypeString, value)
	}
	if tuo.mutation.TagsCleared() {
		_spec.ClearField(test3schema.FieldTags, field.TypeString)
	}
	_node = &Test3Schema{config: tuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{test3schema.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tuo.mutation.done = true
	return _node, nil
}
