// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"transaction-filter-backend/ent/test2schema"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// Test2SchemaCreate is the builder for creating a Test2Schema entity.
type Test2SchemaCreate struct {
	config
	mutation *Test2SchemaMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (tc *Test2SchemaCreate) SetName(s string) *Test2SchemaCreate {
	tc.mutation.SetName(s)
	return tc
}

// SetNillableName sets the "name" field if the given value is not nil.
func (tc *Test2SchemaCreate) SetNillableName(s *string) *Test2SchemaCreate {
	if s != nil {
		tc.SetName(*s)
	}
	return tc
}

// SetDescription sets the "description" field.
func (tc *Test2SchemaCreate) SetDescription(s string) *Test2SchemaCreate {
	tc.mutation.SetDescription(s)
	return tc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (tc *Test2SchemaCreate) SetNillableDescription(s *string) *Test2SchemaCreate {
	if s != nil {
		tc.SetDescription(*s)
	}
	return tc
}

// SetQuantity sets the "quantity" field.
func (tc *Test2SchemaCreate) SetQuantity(i int) *Test2SchemaCreate {
	tc.mutation.SetQuantity(i)
	return tc
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (tc *Test2SchemaCreate) SetNillableQuantity(i *int) *Test2SchemaCreate {
	if i != nil {
		tc.SetQuantity(*i)
	}
	return tc
}

// SetPrice sets the "price" field.
func (tc *Test2SchemaCreate) SetPrice(f float64) *Test2SchemaCreate {
	tc.mutation.SetPrice(f)
	return tc
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (tc *Test2SchemaCreate) SetNillablePrice(f *float64) *Test2SchemaCreate {
	if f != nil {
		tc.SetPrice(*f)
	}
	return tc
}

// SetActive sets the "active" field.
func (tc *Test2SchemaCreate) SetActive(b bool) *Test2SchemaCreate {
	tc.mutation.SetActive(b)
	return tc
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (tc *Test2SchemaCreate) SetNillableActive(b *bool) *Test2SchemaCreate {
	if b != nil {
		tc.SetActive(*b)
	}
	return tc
}

// SetCreatedAt sets the "created_at" field.
func (tc *Test2SchemaCreate) SetCreatedAt(t time.Time) *Test2SchemaCreate {
	tc.mutation.SetCreatedAt(t)
	return tc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tc *Test2SchemaCreate) SetNillableCreatedAt(t *time.Time) *Test2SchemaCreate {
	if t != nil {
		tc.SetCreatedAt(*t)
	}
	return tc
}

// SetUpdatedAt sets the "updated_at" field.
func (tc *Test2SchemaCreate) SetUpdatedAt(t time.Time) *Test2SchemaCreate {
	tc.mutation.SetUpdatedAt(t)
	return tc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (tc *Test2SchemaCreate) SetNillableUpdatedAt(t *time.Time) *Test2SchemaCreate {
	if t != nil {
		tc.SetUpdatedAt(*t)
	}
	return tc
}

// SetItemType sets the "item_type" field.
func (tc *Test2SchemaCreate) SetItemType(s string) *Test2SchemaCreate {
	tc.mutation.SetItemType(s)
	return tc
}

// SetNillableItemType sets the "item_type" field if the given value is not nil.
func (tc *Test2SchemaCreate) SetNillableItemType(s *string) *Test2SchemaCreate {
	if s != nil {
		tc.SetItemType(*s)
	}
	return tc
}

// Mutation returns the Test2SchemaMutation object of the builder.
func (tc *Test2SchemaCreate) Mutation() *Test2SchemaMutation {
	return tc.mutation
}

// Save creates the Test2Schema in the database.
func (tc *Test2SchemaCreate) Save(ctx context.Context) (*Test2Schema, error) {
	tc.defaults()
	return withHooks(ctx, tc.sqlSave, tc.mutation, tc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tc *Test2SchemaCreate) SaveX(ctx context.Context) *Test2Schema {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tc *Test2SchemaCreate) Exec(ctx context.Context) error {
	_, err := tc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tc *Test2SchemaCreate) ExecX(ctx context.Context) {
	if err := tc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tc *Test2SchemaCreate) defaults() {
	if _, ok := tc.mutation.Name(); !ok {
		v := test2schema.DefaultName
		tc.mutation.SetName(v)
	}
	if _, ok := tc.mutation.Quantity(); !ok {
		v := test2schema.DefaultQuantity
		tc.mutation.SetQuantity(v)
	}
	if _, ok := tc.mutation.Price(); !ok {
		v := test2schema.DefaultPrice
		tc.mutation.SetPrice(v)
	}
	if _, ok := tc.mutation.Active(); !ok {
		v := test2schema.DefaultActive
		tc.mutation.SetActive(v)
	}
	if _, ok := tc.mutation.CreatedAt(); !ok {
		v := test2schema.DefaultCreatedAt()
		tc.mutation.SetCreatedAt(v)
	}
	if _, ok := tc.mutation.UpdatedAt(); !ok {
		v := test2schema.DefaultUpdatedAt()
		tc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tc *Test2SchemaCreate) check() error {
	if _, ok := tc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Test2Schema.name"`)}
	}
	if _, ok := tc.mutation.Quantity(); !ok {
		return &ValidationError{Name: "quantity", err: errors.New(`ent: missing required field "Test2Schema.quantity"`)}
	}
	if _, ok := tc.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "Test2Schema.price"`)}
	}
	if _, ok := tc.mutation.Active(); !ok {
		return &ValidationError{Name: "active", err: errors.New(`ent: missing required field "Test2Schema.active"`)}
	}
	if _, ok := tc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Test2Schema.created_at"`)}
	}
	if _, ok := tc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Test2Schema.updated_at"`)}
	}
	return nil
}

func (tc *Test2SchemaCreate) sqlSave(ctx context.Context) (*Test2Schema, error) {
	if err := tc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	tc.mutation.id = &_node.ID
	tc.mutation.done = true
	return _node, nil
}

func (tc *Test2SchemaCreate) createSpec() (*Test2Schema, *sqlgraph.CreateSpec) {
	var (
		_node = &Test2Schema{config: tc.config}
		_spec = sqlgraph.NewCreateSpec(test2schema.Table, sqlgraph.NewFieldSpec(test2schema.FieldID, field.TypeInt))
	)
	if value, ok := tc.mutation.Name(); ok {
		_spec.SetField(test2schema.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := tc.mutation.Description(); ok {
		_spec.SetField(test2schema.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := tc.mutation.Quantity(); ok {
		_spec.SetField(test2schema.FieldQuantity, field.TypeInt, value)
		_node.Quantity = value
	}
	if value, ok := tc.mutation.Price(); ok {
		_spec.SetField(test2schema.FieldPrice, field.TypeFloat64, value)
		_node.Price = value
	}
	if value, ok := tc.mutation.Active(); ok {
		_spec.SetField(test2schema.FieldActive, field.TypeBool, value)
		_node.Active = value
	}
	if value, ok := tc.mutation.CreatedAt(); ok {
		_spec.SetField(test2schema.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := tc.mutation.UpdatedAt(); ok {
		_spec.SetField(test2schema.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := tc.mutation.ItemType(); ok {
		_spec.SetField(test2schema.FieldItemType, field.TypeString, value)
		_node.ItemType = value
	}
	return _node, _spec
}

// Test2SchemaCreateBulk is the builder for creating many Test2Schema entities in bulk.
type Test2SchemaCreateBulk struct {
	config
	err      error
	builders []*Test2SchemaCreate
}

// Save creates the Test2Schema entities in the database.
func (tcb *Test2SchemaCreateBulk) Save(ctx context.Context) ([]*Test2Schema, error) {
	if tcb.err != nil {
		return nil, tcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tcb.builders))
	nodes := make([]*Test2Schema, len(tcb.builders))
	mutators := make([]Mutator, len(tcb.builders))
	for i := range tcb.builders {
		func(i int, root context.Context) {
			builder := tcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*Test2SchemaMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcb *Test2SchemaCreateBulk) SaveX(ctx context.Context) []*Test2Schema {
	v, err := tcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcb *Test2SchemaCreateBulk) Exec(ctx context.Context) error {
	_, err := tcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcb *Test2SchemaCreateBulk) ExecX(ctx context.Context) {
	if err := tcb.Exec(ctx); err != nil {
		panic(err)
	}
}
