// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"transaction-filter-backend/ent/test3schema"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Test3Schema is the model entity for the Test3Schema schema.
type Test3Schema struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Sku holds the value of the "sku" field.
	Sku string `json:"sku,omitempty"`
	// ProductName holds the value of the "product_name" field.
	ProductName string `json:"product_name,omitempty"`
	// ShortDescription holds the value of the "short_description" field.
	ShortDescription string `json:"short_description,omitempty"`
	// FullDescription holds the value of the "full_description" field.
	FullDescription string `json:"full_description,omitempty"`
	// CostPrice holds the value of the "cost_price" field.
	CostPrice float64 `json:"cost_price,omitempty"`
	// RetailPrice holds the value of the "retail_price" field.
	RetailPrice float64 `json:"retail_price,omitempty"`
	// StockCount holds the value of the "stock_count" field.
	StockCount int `json:"stock_count,omitempty"`
	// IsActive holds the value of the "is_active" field.
	IsActive bool `json:"is_active,omitempty"`
	// PublishedAt holds the value of the "published_at" field.
	PublishedAt time.Time `json:"published_at,omitempty"`
	// LastOrderedAt holds the value of the "last_ordered_at" field.
	LastOrderedAt time.Time `json:"last_ordered_at,omitempty"`
	// Comma-separated tags
	Tags         string `json:"tags,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Test3Schema) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case test3schema.FieldIsActive:
			values[i] = new(sql.NullBool)
		case test3schema.FieldCostPrice, test3schema.FieldRetailPrice:
			values[i] = new(sql.NullFloat64)
		case test3schema.FieldID, test3schema.FieldStockCount:
			values[i] = new(sql.NullInt64)
		case test3schema.FieldSku, test3schema.FieldProductName, test3schema.FieldShortDescription, test3schema.FieldFullDescription, test3schema.FieldTags:
			values[i] = new(sql.NullString)
		case test3schema.FieldPublishedAt, test3schema.FieldLastOrderedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Test3Schema fields.
func (t *Test3Schema) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case test3schema.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			t.ID = int(value.Int64)
		case test3schema.FieldSku:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sku", values[i])
			} else if value.Valid {
				t.Sku = value.String
			}
		case test3schema.FieldProductName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field product_name", values[i])
			} else if value.Valid {
				t.ProductName = value.String
			}
		case test3schema.FieldShortDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field short_description", values[i])
			} else if value.Valid {
				t.ShortDescription = value.String
			}
		case test3schema.FieldFullDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field full_description", values[i])
			} else if value.Valid {
				t.FullDescription = value.String
			}
		case test3schema.FieldCostPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cost_price", values[i])
			} else if value.Valid {
				t.CostPrice = value.Float64
			}
		case test3schema.FieldRetailPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field retail_price", values[i])
			} else if value.Valid {
				t.RetailPrice = value.Float64
			}
		case test3schema.FieldStockCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field stock_count", values[i])
			} else if value.Valid {
				t.StockCount = int(value.Int64)
			}
		case test3schema.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				t.IsActive = value.Bool
			}
		case test3schema.FieldPublishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field published_at", values[i])
			} else if value.Valid {
				t.PublishedAt = value.Time
			}
		case test3schema.FieldLastOrderedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_ordered_at", values[i])
			} else if value.Valid {
				t.LastOrderedAt = value.Time
			}
		case test3schema.FieldTags:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tags", values[i])
			} else if value.Valid {
				t.Tags = value.String
			}
		default:
			t.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Test3Schema.
// This includes values selected through modifiers, order, etc.
func (t *Test3Schema) Value(name string) (ent.Value, error) {
	return t.selectValues.Get(name)
}

// Update returns a builder for updating this Test3Schema.
// Note that you need to call Test3Schema.Unwrap() before calling this method if this Test3Schema
// was returned from a transaction, and the transaction was committed or rolled back.
func (t *Test3Schema) Update() *Test3SchemaUpdateOne {
	return NewTest3SchemaClient(t.config).UpdateOne(t)
}

// Unwrap unwraps the Test3Schema entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (t *Test3Schema) Unwrap() *Test3Schema {
	_tx, ok := t.config.driver.(*txDriver)
	if !ok {
		panic("ent: Test3Schema is not a transactional entity")
	}
	t.config.driver = _tx.drv
	return t
}

// String implements the fmt.Stringer.
func (t *Test3Schema) String() string {
	var builder strings.Builder
	builder.WriteString("Test3Schema(")
	builder.WriteString(fmt.Sprintf("id=%v, ", t.ID))
	builder.WriteString("sku=")
	builder.WriteString(t.Sku)
	builder.WriteString(", ")
	builder.WriteString("product_name=")
	builder.WriteString(t.ProductName)
	builder.WriteString(", ")
	builder.WriteString("short_description=")
	builder.WriteString(t.ShortDescription)
	builder.WriteString(", ")
	builder.WriteString("full_description=")
	builder.WriteString(t.FullDescription)
	builder.WriteString(", ")
	builder.WriteString("cost_price=")
	builder.WriteString(fmt.Sprintf("%v", t.CostPrice))
	builder.WriteString(", ")
	builder.WriteString("retail_price=")
	builder.WriteString(fmt.Sprintf("%v", t.RetailPrice))
	builder.WriteString(", ")
	builder.WriteString("stock_count=")
	builder.WriteString(fmt.Sprintf("%v", t.StockCount))
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", t.IsActive))
	builder.WriteString(", ")
	builder.WriteString("published_at=")
	builder.WriteString(t.PublishedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("last_ordered_at=")
	builder.WriteString(t.LastOrderedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("tags=")
	builder.WriteString(t.Tags)
	builder.WriteByte(')')
	return builder.String()
}

// Test3Schemas is a parsable slice of Test3Schema.
type Test3Schemas []*Test3Schema
