// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"transaction-filter-backend/ent/predicate"
	"transaction-filter-backend/ent/test1schema"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// Test1SchemaUpdate is the builder for updating Test1Schema entities.
type Test1SchemaUpdate struct {
	config
	hooks    []Hook
	mutation *Test1SchemaMutation
}

// Where appends a list predicates to the Test1SchemaUpdate builder.
func (tu *Test1SchemaUpdate) Where(ps ...predicate.Test1Schema) *Test1SchemaUpdate {
	tu.mutation.Where(ps...)
	return tu
}

// SetFieldString sets the "field_string" field.
func (tu *Test1SchemaUpdate) SetFieldString(s string) *Test1SchemaUpdate {
	tu.mutation.SetFieldString(s)
	return tu
}

// SetNillableFieldString sets the "field_string" field if the given value is not nil.
func (tu *Test1SchemaUpdate) SetNillableFieldString(s *string) *Test1SchemaUpdate {
	if s != nil {
		tu.SetFieldString(*s)
	}
	return tu
}

// SetFieldInt sets the "field_int" field.
func (tu *Test1SchemaUpdate) SetFieldInt(i int) *Test1SchemaUpdate {
	tu.mutation.ResetFieldInt()
	tu.mutation.SetFieldInt(i)
	return tu
}

// SetNillableFieldInt sets the "field_int" field if the given value is not nil.
func (tu *Test1SchemaUpdate) SetNillableFieldInt(i *int) *Test1SchemaUpdate {
	if i != nil {
		tu.SetFieldInt(*i)
	}
	return tu
}

// AddFieldInt adds i to the "field_int" field.
func (tu *Test1SchemaUpdate) AddFieldInt(i int) *Test1SchemaUpdate {
	tu.mutation.AddFieldInt(i)
	return tu
}

// SetFieldFloat sets the "field_float" field.
func (tu *Test1SchemaUpdate) SetFieldFloat(f float64) *Test1SchemaUpdate {
	tu.mutation.ResetFieldFloat()
	tu.mutation.SetFieldFloat(f)
	return tu
}

// SetNillableFieldFloat sets the "field_float" field if the given value is not nil.
func (tu *Test1SchemaUpdate) SetNillableFieldFloat(f *float64) *Test1SchemaUpdate {
	if f != nil {
		tu.SetFieldFloat(*f)
	}
	return tu
}

// AddFieldFloat adds f to the "field_float" field.
func (tu *Test1SchemaUpdate) AddFieldFloat(f float64) *Test1SchemaUpdate {
	tu.mutation.AddFieldFloat(f)
	return tu
}

// SetFieldBool sets the "field_bool" field.
func (tu *Test1SchemaUpdate) SetFieldBool(b bool) *Test1SchemaUpdate {
	tu.mutation.SetFieldBool(b)
	return tu
}

// SetNillableFieldBool sets the "field_bool" field if the given value is not nil.
func (tu *Test1SchemaUpdate) SetNillableFieldBool(b *bool) *Test1SchemaUpdate {
	if b != nil {
		tu.SetFieldBool(*b)
	}
	return tu
}

// SetFieldTime sets the "field_time" field.
func (tu *Test1SchemaUpdate) SetFieldTime(t time.Time) *Test1SchemaUpdate {
	tu.mutation.SetFieldTime(t)
	return tu
}

// SetNillableFieldTime sets the "field_time" field if the given value is not nil.
func (tu *Test1SchemaUpdate) SetNillableFieldTime(t *time.Time) *Test1SchemaUpdate {
	if t != nil {
		tu.SetFieldTime(*t)
	}
	return tu
}

// SetFieldText sets the "field_text" field.
func (tu *Test1SchemaUpdate) SetFieldText(s string) *Test1SchemaUpdate {
	tu.mutation.SetFieldText(s)
	return tu
}

// SetNillableFieldText sets the "field_text" field if the given value is not nil.
func (tu *Test1SchemaUpdate) SetNillableFieldText(s *string) *Test1SchemaUpdate {
	if s != nil {
		tu.SetFieldText(*s)
	}
	return tu
}

// ClearFieldText clears the value of the "field_text" field.
func (tu *Test1SchemaUpdate) ClearFieldText() *Test1SchemaUpdate {
	tu.mutation.ClearFieldText()
	return tu
}

// Mutation returns the Test1SchemaMutation object of the builder.
func (tu *Test1SchemaUpdate) Mutation() *Test1SchemaMutation {
	return tu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tu *Test1SchemaUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, tu.sqlSave, tu.mutation, tu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tu *Test1SchemaUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *Test1SchemaUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *Test1SchemaUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tu *Test1SchemaUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(test1schema.Table, test1schema.Columns, sqlgraph.NewFieldSpec(test1schema.FieldID, field.TypeInt))
	if ps := tu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.FieldString(); ok {
		_spec.SetField(test1schema.FieldFieldString, field.TypeString, value)
	}
	if value, ok := tu.mutation.FieldInt(); ok {
		_spec.SetField(test1schema.FieldFieldInt, field.TypeInt, value)
	}
	if value, ok := tu.mutation.AddedFieldInt(); ok {
		_spec.AddField(test1schema.FieldFieldInt, field.TypeInt, value)
	}
	if value, ok := tu.mutation.FieldFloat(); ok {
		_spec.SetField(test1schema.FieldFieldFloat, field.TypeFloat64, value)
	}
	if value, ok := tu.mutation.AddedFieldFloat(); ok {
		_spec.AddField(test1schema.FieldFieldFloat, field.TypeFloat64, value)
	}
	if value, ok := tu.mutation.FieldBool(); ok {
		_spec.SetField(test1schema.FieldFieldBool, field.TypeBool, value)
	}
	if value, ok := tu.mutation.FieldTime(); ok {
		_spec.SetField(test1schema.FieldFieldTime, field.TypeTime, value)
	}
	if value, ok := tu.mutation.FieldText(); ok {
		_spec.SetField(test1schema.FieldFieldText, field.TypeString, value)
	}
	if tu.mutation.FieldTextCleared() {
		_spec.ClearField(test1schema.FieldFieldText, field.TypeString)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{test1schema.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tu.mutation.done = true
	return n, nil
}

// Test1SchemaUpdateOne is the builder for updating a single Test1Schema entity.
type Test1SchemaUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *Test1SchemaMutation
}

// SetFieldString sets the "field_string" field.
func (tuo *Test1SchemaUpdateOne) SetFieldString(s string) *Test1SchemaUpdateOne {
	tuo.mutation.SetFieldString(s)
	return tuo
}

// SetNillableFieldString sets the "field_string" field if the given value is not nil.
func (tuo *Test1SchemaUpdateOne) SetNillableFieldString(s *string) *Test1SchemaUpdateOne {
	if s != nil {
		tuo.SetFieldString(*s)
	}
	return tuo
}

// SetFieldInt sets the "field_int" field.
func (tuo *Test1SchemaUpdateOne) SetFieldInt(i int) *Test1SchemaUpdateOne {
	tuo.mutation.ResetFieldInt()
	tuo.mutation.SetFieldInt(i)
	return tuo
}

// SetNillableFieldInt sets the "field_int" field if the given value is not nil.
func (tuo *Test1SchemaUpdateOne) SetNillableFieldInt(i *int) *Test1SchemaUpdateOne {
	if i != nil {
		tuo.SetFieldInt(*i)
	}
	return tuo
}

// AddFieldInt adds i to the "field_int" field.
func (tuo *Test1SchemaUpdateOne) AddFieldInt(i int) *Test1SchemaUpdateOne {
	tuo.mutation.AddFieldInt(i)
	return tuo
}

// SetFieldFloat sets the "field_float" field.
func (tuo *Test1SchemaUpdateOne) SetFieldFloat(f float64) *Test1SchemaUpdateOne {
	tuo.mutation.ResetFieldFloat()
	tuo.mutation.SetFieldFloat(f)
	return tuo
}

// SetNillableFieldFloat sets the "field_float" field if the given value is not nil.
func (tuo *Test1SchemaUpdateOne) SetNillableFieldFloat(f *float64) *Test1SchemaUpdateOne {
	if f != nil {
		tuo.SetFieldFloat(*f)
	}
	return tuo
}

// AddFieldFloat adds f to the "field_float" field.
func (tuo *Test1SchemaUpdateOne) AddFieldFloat(f float64) *Test1SchemaUpdateOne {
	tuo.mutation.AddFieldFloat(f)
	return tuo
}

// SetFieldBool sets the "field_bool" field.
func (tuo *Test1SchemaUpdateOne) SetFieldBool(b bool) *Test1SchemaUpdateOne {
	tuo.mutation.SetFieldBool(b)
	return tuo
}

// SetNillableFieldBool sets the "field_bool" field if the given value is not nil.
func (tuo *Test1SchemaUpdateOne) SetNillableFieldBool(b *bool) *Test1SchemaUpdateOne {
	if b != nil {
		tuo.SetFieldBool(*b)
	}
	return tuo
}

// SetFieldTime sets the "field_time" field.
func (tuo *Test1SchemaUpdateOne) SetFieldTime(t time.Time) *Test1SchemaUpdateOne {
	tuo.mutation.SetFieldTime(t)
	return tuo
}

// SetNillableFieldTime sets the "field_time" field if the given value is not nil.
func (tuo *Test1SchemaUpdateOne) SetNillableFieldTime(t *time.Time) *Test1SchemaUpdateOne {
	if t != nil {
		tuo.SetFieldTime(*t)
	}
	return tuo
}

// SetFieldText sets the "field_text" field.
func (tuo *Test1SchemaUpdateOne) SetFieldText(s string) *Test1SchemaUpdateOne {
	tuo.mutation.SetFieldText(s)
	return tuo
}

// SetNillableFieldText sets the "field_text" field if the given value is not nil.
func (tuo *Test1SchemaUpdateOne) SetNillableFieldText(s *string) *Test1SchemaUpdateOne {
	if s != nil {
		tuo.SetFieldText(*s)
	}
	return tuo
}

// ClearFieldText clears the value of the "field_text" field.
func (tuo *Test1SchemaUpdateOne) ClearFieldText() *Test1SchemaUpdateOne {
	tuo.mutation.ClearFieldText()
	return tuo
}

// Mutation returns the Test1SchemaMutation object of the builder.
func (tuo *Test1SchemaUpdateOne) Mutation() *Test1SchemaMutation {
	return tuo.mutation
}

// Where appends a list predicates to the Test1SchemaUpdate builder.
func (tuo *Test1SchemaUpdateOne) Where(ps ...predicate.Test1Schema) *Test1SchemaUpdateOne {
	tuo.mutation.Where(ps...)
	return tuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tuo *Test1SchemaUpdateOne) Select(field string, fields ...string) *Test1SchemaUpdateOne {
	tuo.fields = append([]string{field}, fields...)
	return tuo
}

// Save executes the query and returns the updated Test1Schema entity.
func (tuo *Test1SchemaUpdateOne) Save(ctx context.Context) (*Test1Schema, error) {
	return withHooks(ctx, tuo.sqlSave, tuo.mutation, tuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *Test1SchemaUpdateOne) SaveX(ctx context.Context) *Test1Schema {
	node, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tuo *Test1SchemaUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *Test1SchemaUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tuo *Test1SchemaUpdateOne) sqlSave(ctx context.Context) (_node *Test1Schema, err error) {
	_spec := sqlgraph.NewUpdateSpec(test1schema.Table, test1schema.Columns, sqlgraph.NewFieldSpec(test1schema.FieldID, field.TypeInt))
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Test1Schema.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, test1schema.FieldID)
		for _, f := range fields {
			if !test1schema.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != test1schema.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuo.mutation.FieldString(); ok {
		_spec.SetField(test1schema.FieldFieldString, field.TypeString, value)
	}
	if value, ok := tuo.mutation.FieldInt(); ok {
		_spec.SetField(test1schema.FieldFieldInt, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.AddedFieldInt(); ok {
		_spec.AddField(test1schema.FieldFieldInt, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.FieldFloat(); ok {
		_spec.SetField(test1schema.FieldFieldFloat, field.TypeFloat64, value)
	}
	if value, ok := tuo.mutation.AddedFieldFloat(); ok {
		_spec.AddField(test1schema.FieldFieldFloat, field.TypeFloat64, value)
	}
	if value, ok := tuo.mutation.FieldBool(); ok {
		_spec.SetField(test1schema.FieldFieldBool, field.TypeBool, value)
	}
	if value, ok := tuo.mutation.FieldTime(); ok {
		_spec.SetField(test1schema.FieldFieldTime, field.TypeTime, value)
	}
	if value, ok := tuo.mutation.FieldText(); ok {
		_spec.SetField(test1schema.FieldFieldText, field.TypeString, value)
	}
	if tuo.mutation.FieldTextCleared() {
		_spec.ClearField(test1schema.FieldFieldText, field.TypeString)
	}
	_node = &Test1Schema{config: tuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{test1schema.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tuo.mutation.done = true
	return _node, nil
}
