// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"transaction-filter-backend/ent/test1schema"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// Test1SchemaCreate is the builder for creating a Test1Schema entity.
type Test1SchemaCreate struct {
	config
	mutation *Test1SchemaMutation
	hooks    []Hook
}

// SetFieldString sets the "field_string" field.
func (tc *Test1SchemaCreate) SetFieldString(s string) *Test1SchemaCreate {
	tc.mutation.SetFieldString(s)
	return tc
}

// SetNillableFieldString sets the "field_string" field if the given value is not nil.
func (tc *Test1SchemaCreate) SetNillableFieldString(s *string) *Test1SchemaCreate {
	if s != nil {
		tc.SetFieldString(*s)
	}
	return tc
}

// SetFieldInt sets the "field_int" field.
func (tc *Test1SchemaCreate) SetFieldInt(i int) *Test1SchemaCreate {
	tc.mutation.SetFieldInt(i)
	return tc
}

// SetNillableFieldInt sets the "field_int" field if the given value is not nil.
func (tc *Test1SchemaCreate) SetNillableFieldInt(i *int) *Test1SchemaCreate {
	if i != nil {
		tc.SetFieldInt(*i)
	}
	return tc
}

// SetFieldFloat sets the "field_float" field.
func (tc *Test1SchemaCreate) SetFieldFloat(f float64) *Test1SchemaCreate {
	tc.mutation.SetFieldFloat(f)
	return tc
}

// SetNillableFieldFloat sets the "field_float" field if the given value is not nil.
func (tc *Test1SchemaCreate) SetNillableFieldFloat(f *float64) *Test1SchemaCreate {
	if f != nil {
		tc.SetFieldFloat(*f)
	}
	return tc
}

// SetFieldBool sets the "field_bool" field.
func (tc *Test1SchemaCreate) SetFieldBool(b bool) *Test1SchemaCreate {
	tc.mutation.SetFieldBool(b)
	return tc
}

// SetNillableFieldBool sets the "field_bool" field if the given value is not nil.
func (tc *Test1SchemaCreate) SetNillableFieldBool(b *bool) *Test1SchemaCreate {
	if b != nil {
		tc.SetFieldBool(*b)
	}
	return tc
}

// SetFieldTime sets the "field_time" field.
func (tc *Test1SchemaCreate) SetFieldTime(t time.Time) *Test1SchemaCreate {
	tc.mutation.SetFieldTime(t)
	return tc
}

// SetNillableFieldTime sets the "field_time" field if the given value is not nil.
func (tc *Test1SchemaCreate) SetNillableFieldTime(t *time.Time) *Test1SchemaCreate {
	if t != nil {
		tc.SetFieldTime(*t)
	}
	return tc
}

// SetFieldText sets the "field_text" field.
func (tc *Test1SchemaCreate) SetFieldText(s string) *Test1SchemaCreate {
	tc.mutation.SetFieldText(s)
	return tc
}

// SetNillableFieldText sets the "field_text" field if the given value is not nil.
func (tc *Test1SchemaCreate) SetNillableFieldText(s *string) *Test1SchemaCreate {
	if s != nil {
		tc.SetFieldText(*s)
	}
	return tc
}

// Mutation returns the Test1SchemaMutation object of the builder.
func (tc *Test1SchemaCreate) Mutation() *Test1SchemaMutation {
	return tc.mutation
}

// Save creates the Test1Schema in the database.
func (tc *Test1SchemaCreate) Save(ctx context.Context) (*Test1Schema, error) {
	tc.defaults()
	return withHooks(ctx, tc.sqlSave, tc.mutation, tc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tc *Test1SchemaCreate) SaveX(ctx context.Context) *Test1Schema {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tc *Test1SchemaCreate) Exec(ctx context.Context) error {
	_, err := tc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tc *Test1SchemaCreate) ExecX(ctx context.Context) {
	if err := tc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tc *Test1SchemaCreate) defaults() {
	if _, ok := tc.mutation.FieldString(); !ok {
		v := test1schema.DefaultFieldString
		tc.mutation.SetFieldString(v)
	}
	if _, ok := tc.mutation.FieldInt(); !ok {
		v := test1schema.DefaultFieldInt
		tc.mutation.SetFieldInt(v)
	}
	if _, ok := tc.mutation.FieldFloat(); !ok {
		v := test1schema.DefaultFieldFloat
		tc.mutation.SetFieldFloat(v)
	}
	if _, ok := tc.mutation.FieldBool(); !ok {
		v := test1schema.DefaultFieldBool
		tc.mutation.SetFieldBool(v)
	}
	if _, ok := tc.mutation.FieldTime(); !ok {
		v := test1schema.DefaultFieldTime()
		tc.mutation.SetFieldTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tc *Test1SchemaCreate) check() error {
	if _, ok := tc.mutation.FieldString(); !ok {
		return &ValidationError{Name: "field_string", err: errors.New(`ent: missing required field "Test1Schema.field_string"`)}
	}
	if _, ok := tc.mutation.FieldInt(); !ok {
		return &ValidationError{Name: "field_int", err: errors.New(`ent: missing required field "Test1Schema.field_int"`)}
	}
	if _, ok := tc.mutation.FieldFloat(); !ok {
		return &ValidationError{Name: "field_float", err: errors.New(`ent: missing required field "Test1Schema.field_float"`)}
	}
	if _, ok := tc.mutation.FieldBool(); !ok {
		return &ValidationError{Name: "field_bool", err: errors.New(`ent: missing required field "Test1Schema.field_bool"`)}
	}
	if _, ok := tc.mutation.FieldTime(); !ok {
		return &ValidationError{Name: "field_time", err: errors.New(`ent: missing required field "Test1Schema.field_time"`)}
	}
	return nil
}

func (tc *Test1SchemaCreate) sqlSave(ctx context.Context) (*Test1Schema, error) {
	if err := tc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	tc.mutation.id = &_node.ID
	tc.mutation.done = true
	return _node, nil
}

func (tc *Test1SchemaCreate) createSpec() (*Test1Schema, *sqlgraph.CreateSpec) {
	var (
		_node = &Test1Schema{config: tc.config}
		_spec = sqlgraph.NewCreateSpec(test1schema.Table, sqlgraph.NewFieldSpec(test1schema.FieldID, field.TypeInt))
	)
	if value, ok := tc.mutation.FieldString(); ok {
		_spec.SetField(test1schema.FieldFieldString, field.TypeString, value)
		_node.FieldString = value
	}
	if value, ok := tc.mutation.FieldInt(); ok {
		_spec.SetField(test1schema.FieldFieldInt, field.TypeInt, value)
		_node.FieldInt = value
	}
	if value, ok := tc.mutation.FieldFloat(); ok {
		_spec.SetField(test1schema.FieldFieldFloat, field.TypeFloat64, value)
		_node.FieldFloat = value
	}
	if value, ok := tc.mutation.FieldBool(); ok {
		_spec.SetField(test1schema.FieldFieldBool, field.TypeBool, value)
		_node.FieldBool = value
	}
	if value, ok := tc.mutation.FieldTime(); ok {
		_spec.SetField(test1schema.FieldFieldTime, field.TypeTime, value)
		_node.FieldTime = value
	}
	if value, ok := tc.mutation.FieldText(); ok {
		_spec.SetField(test1schema.FieldFieldText, field.TypeString, value)
		_node.FieldText = value
	}
	return _node, _spec
}

// Test1SchemaCreateBulk is the builder for creating many Test1Schema entities in bulk.
type Test1SchemaCreateBulk struct {
	config
	err      error
	builders []*Test1SchemaCreate
}

// Save creates the Test1Schema entities in the database.
func (tcb *Test1SchemaCreateBulk) Save(ctx context.Context) ([]*Test1Schema, error) {
	if tcb.err != nil {
		return nil, tcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tcb.builders))
	nodes := make([]*Test1Schema, len(tcb.builders))
	mutators := make([]Mutator, len(tcb.builders))
	for i := range tcb.builders {
		func(i int, root context.Context) {
			builder := tcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*Test1SchemaMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcb *Test1SchemaCreateBulk) SaveX(ctx context.Context) []*Test1Schema {
	v, err := tcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcb *Test1SchemaCreateBulk) Exec(ctx context.Context) error {
	_, err := tcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcb *Test1SchemaCreateBulk) ExecX(ctx context.Context) {
	if err := tcb.Exec(ctx); err != nil {
		panic(err)
	}
}
