// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"transaction-filter-backend/ent/predicate"
	"transaction-filter-backend/ent/test1schema"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// Test1SchemaDelete is the builder for deleting a Test1Schema entity.
type Test1SchemaDelete struct {
	config
	hooks    []Hook
	mutation *Test1SchemaMutation
}

// Where appends a list predicates to the Test1SchemaDelete builder.
func (td *Test1SchemaDelete) Where(ps ...predicate.Test1Schema) *Test1SchemaDelete {
	td.mutation.Where(ps...)
	return td
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (td *Test1SchemaDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, td.sqlExec, td.mutation, td.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (td *Test1SchemaDelete) ExecX(ctx context.Context) int {
	n, err := td.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (td *Test1SchemaDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(test1schema.Table, sqlgraph.NewFieldSpec(test1schema.FieldID, field.TypeInt))
	if ps := td.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, td.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	td.mutation.done = true
	return affected, err
}

// Test1SchemaDeleteOne is the builder for deleting a single Test1Schema entity.
type Test1SchemaDeleteOne struct {
	td *Test1SchemaDelete
}

// Where appends a list predicates to the Test1SchemaDelete builder.
func (tdo *Test1SchemaDeleteOne) Where(ps ...predicate.Test1Schema) *Test1SchemaDeleteOne {
	tdo.td.mutation.Where(ps...)
	return tdo
}

// Exec executes the deletion query.
func (tdo *Test1SchemaDeleteOne) Exec(ctx context.Context) error {
	n, err := tdo.td.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{test1schema.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tdo *Test1SchemaDeleteOne) ExecX(ctx context.Context) {
	if err := tdo.Exec(ctx); err != nil {
		panic(err)
	}
}
