// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"transaction-filter-backend/ent/test3schema"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// Test3SchemaCreate is the builder for creating a Test3Schema entity.
type Test3SchemaCreate struct {
	config
	mutation *Test3SchemaMutation
	hooks    []Hook
}

// SetSku sets the "sku" field.
func (tc *Test3SchemaCreate) SetSku(s string) *Test3SchemaCreate {
	tc.mutation.SetSku(s)
	return tc
}

// SetProductName sets the "product_name" field.
func (tc *Test3SchemaCreate) SetProductName(s string) *Test3SchemaCreate {
	tc.mutation.SetProductName(s)
	return tc
}

// SetNillableProductName sets the "product_name" field if the given value is not nil.
func (tc *Test3SchemaCreate) SetNillableProductName(s *string) *Test3SchemaCreate {
	if s != nil {
		tc.SetProductName(*s)
	}
	return tc
}

// SetShortDescription sets the "short_description" field.
func (tc *Test3SchemaCreate) SetShortDescription(s string) *Test3SchemaCreate {
	tc.mutation.SetShortDescription(s)
	return tc
}

// SetNillableShortDescription sets the "short_description" field if the given value is not nil.
func (tc *Test3SchemaCreate) SetNillableShortDescription(s *string) *Test3SchemaCreate {
	if s != nil {
		tc.SetShortDescription(*s)
	}
	return tc
}

// SetFullDescription sets the "full_description" field.
func (tc *Test3SchemaCreate) SetFullDescription(s string) *Test3SchemaCreate {
	tc.mutation.SetFullDescription(s)
	return tc
}

// SetNillableFullDescription sets the "full_description" field if the given value is not nil.
func (tc *Test3SchemaCreate) SetNillableFullDescription(s *string) *Test3SchemaCreate {
	if s != nil {
		tc.SetFullDescription(*s)
	}
	return tc
}

// SetCostPrice sets the "cost_price" field.
func (tc *Test3SchemaCreate) SetCostPrice(f float64) *Test3SchemaCreate {
	tc.mutation.SetCostPrice(f)
	return tc
}

// SetNillableCostPrice sets the "cost_price" field if the given value is not nil.
func (tc *Test3SchemaCreate) SetNillableCostPrice(f *float64) *Test3SchemaCreate {
	if f != nil {
		tc.SetCostPrice(*f)
	}
	return tc
}

// SetRetailPrice sets the "retail_price" field.
func (tc *Test3SchemaCreate) SetRetailPrice(f float64) *Test3SchemaCreate {
	tc.mutation.SetRetailPrice(f)
	return tc
}

// SetNillableRetailPrice sets the "retail_price" field if the given value is not nil.
func (tc *Test3SchemaCreate) SetNillableRetailPrice(f *float64) *Test3SchemaCreate {
	if f != nil {
		tc.SetRetailPrice(*f)
	}
	return tc
}

// SetStockCount sets the "stock_count" field.
func (tc *Test3SchemaCreate) SetStockCount(i int) *Test3SchemaCreate {
	tc.mutation.SetStockCount(i)
	return tc
}

// SetNillableStockCount sets the "stock_count" field if the given value is not nil.
func (tc *Test3SchemaCreate) SetNillableStockCount(i *int) *Test3SchemaCreate {
	if i != nil {
		tc.SetStockCount(*i)
	}
	return tc
}

// SetIsActive sets the "is_active" field.
func (tc *Test3SchemaCreate) SetIsActive(b bool) *Test3SchemaCreate {
	tc.mutation.SetIsActive(b)
	return tc
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (tc *Test3SchemaCreate) SetNillableIsActive(b *bool) *Test3SchemaCreate {
	if b != nil {
		tc.SetIsActive(*b)
	}
	return tc
}

// SetPublishedAt sets the "published_at" field.
func (tc *Test3SchemaCreate) SetPublishedAt(t time.Time) *Test3SchemaCreate {
	tc.mutation.SetPublishedAt(t)
	return tc
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (tc *Test3SchemaCreate) SetNillablePublishedAt(t *time.Time) *Test3SchemaCreate {
	if t != nil {
		tc.SetPublishedAt(*t)
	}
	return tc
}

// SetLastOrderedAt sets the "last_ordered_at" field.
func (tc *Test3SchemaCreate) SetLastOrderedAt(t time.Time) *Test3SchemaCreate {
	tc.mutation.SetLastOrderedAt(t)
	return tc
}

// SetNillableLastOrderedAt sets the "last_ordered_at" field if the given value is not nil.
func (tc *Test3SchemaCreate) SetNillableLastOrderedAt(t *time.Time) *Test3SchemaCreate {
	if t != nil {
		tc.SetLastOrderedAt(*t)
	}
	return tc
}

// SetTags sets the "tags" field.
func (tc *Test3SchemaCreate) SetTags(s string) *Test3SchemaCreate {
	tc.mutation.SetTags(s)
	return tc
}

// SetNillableTags sets the "tags" field if the given value is not nil.
func (tc *Test3SchemaCreate) SetNillableTags(s *string) *Test3SchemaCreate {
	if s != nil {
		tc.SetTags(*s)
	}
	return tc
}

// Mutation returns the Test3SchemaMutation object of the builder.
func (tc *Test3SchemaCreate) Mutation() *Test3SchemaMutation {
	return tc.mutation
}

// Save creates the Test3Schema in the database.
func (tc *Test3SchemaCreate) Save(ctx context.Context) (*Test3Schema, error) {
	tc.defaults()
	return withHooks(ctx, tc.sqlSave, tc.mutation, tc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tc *Test3SchemaCreate) SaveX(ctx context.Context) *Test3Schema {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tc *Test3SchemaCreate) Exec(ctx context.Context) error {
	_, err := tc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tc *Test3SchemaCreate) ExecX(ctx context.Context) {
	if err := tc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tc *Test3SchemaCreate) defaults() {
	if _, ok := tc.mutation.ProductName(); !ok {
		v := test3schema.DefaultProductName
		tc.mutation.SetProductName(v)
	}
	if _, ok := tc.mutation.CostPrice(); !ok {
		v := test3schema.DefaultCostPrice
		tc.mutation.SetCostPrice(v)
	}
	if _, ok := tc.mutation.RetailPrice(); !ok {
		v := test3schema.DefaultRetailPrice
		tc.mutation.SetRetailPrice(v)
	}
	if _, ok := tc.mutation.StockCount(); !ok {
		v := test3schema.DefaultStockCount
		tc.mutation.SetStockCount(v)
	}
	if _, ok := tc.mutation.IsActive(); !ok {
		v := test3schema.DefaultIsActive
		tc.mutation.SetIsActive(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tc *Test3SchemaCreate) check() error {
	if _, ok := tc.mutation.Sku(); !ok {
		return &ValidationError{Name: "sku", err: errors.New(`ent: missing required field "Test3Schema.sku"`)}
	}
	if v, ok := tc.mutation.Sku(); ok {
		if err := test3schema.SkuValidator(v); err != nil {
			return &ValidationError{Name: "sku", err: fmt.Errorf(`ent: validator failed for field "Test3Schema.sku": %w`, err)}
		}
	}
	if _, ok := tc.mutation.ProductName(); !ok {
		return &ValidationError{Name: "product_name", err: errors.New(`ent: missing required field "Test3Schema.product_name"`)}
	}
	if _, ok := tc.mutation.CostPrice(); !ok {
		return &ValidationError{Name: "cost_price", err: errors.New(`ent: missing required field "Test3Schema.cost_price"`)}
	}
	if _, ok := tc.mutation.RetailPrice(); !ok {
		return &ValidationError{Name: "retail_price", err: errors.New(`ent: missing required field "Test3Schema.retail_price"`)}
	}
	if _, ok := tc.mutation.StockCount(); !ok {
		return &ValidationError{Name: "stock_count", err: errors.New(`ent: missing required field "Test3Schema.stock_count"`)}
	}
	if _, ok := tc.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "Test3Schema.is_active"`)}
	}
	return nil
}

func (tc *Test3SchemaCreate) sqlSave(ctx context.Context) (*Test3Schema, error) {
	if err := tc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	tc.mutation.id = &_node.ID
	tc.mutation.done = true
	return _node, nil
}

func (tc *Test3SchemaCreate) createSpec() (*Test3Schema, *sqlgraph.CreateSpec) {
	var (
		_node = &Test3Schema{config: tc.config}
		_spec = sqlgraph.NewCreateSpec(test3schema.Table, sqlgraph.NewFieldSpec(test3schema.FieldID, field.TypeInt))
	)
	if value, ok := tc.mutation.Sku(); ok {
		_spec.SetField(test3schema.FieldSku, field.TypeString, value)
		_node.Sku = value
	}
	if value, ok := tc.mutation.ProductName(); ok {
		_spec.SetField(test3schema.FieldProductName, field.TypeString, value)
		_node.ProductName = value
	}
	if value, ok := tc.mutation.ShortDescription(); ok {
		_spec.SetField(test3schema.FieldShortDescription, field.TypeString, value)
		_node.ShortDescription = value
	}
	if value, ok := tc.mutation.FullDescription(); ok {
		_spec.SetField(test3schema.FieldFullDescription, field.TypeString, value)
		_node.FullDescription = value
	}
	if value, ok := tc.mutation.CostPrice(); ok {
		_spec.SetField(test3schema.FieldCostPrice, field.TypeFloat64, value)
		_node.CostPrice = value
	}
	if value, ok := tc.mutation.RetailPrice(); ok {
		_spec.SetField(test3schema.FieldRetailPrice, field.TypeFloat64, value)
		_node.RetailPrice = value
	}
	if value, ok := tc.mutation.StockCount(); ok {
		_spec.SetField(test3schema.FieldStockCount, field.TypeInt, value)
		_node.StockCount = value
	}
	if value, ok := tc.mutation.IsActive(); ok {
		_spec.SetField(test3schema.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := tc.mutation.PublishedAt(); ok {
		_spec.SetField(test3schema.FieldPublishedAt, field.TypeTime, value)
		_node.PublishedAt = value
	}
	if value, ok := tc.mutation.LastOrderedAt(); ok {
		_spec.SetField(test3schema.FieldLastOrderedAt, field.TypeTime, value)
		_node.LastOrderedAt = value
	}
	if value, ok := tc.mutation.Tags(); ok {
		_spec.SetField(test3schema.FieldTags, field.TypeString, value)
		_node.Tags = value
	}
	return _node, _spec
}

// Test3SchemaCreateBulk is the builder for creating many Test3Schema entities in bulk.
type Test3SchemaCreateBulk struct {
	config
	err      error
	builders []*Test3SchemaCreate
}

// Save creates the Test3Schema entities in the database.
func (tcb *Test3SchemaCreateBulk) Save(ctx context.Context) ([]*Test3Schema, error) {
	if tcb.err != nil {
		return nil, tcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tcb.builders))
	nodes := make([]*Test3Schema, len(tcb.builders))
	mutators := make([]Mutator, len(tcb.builders))
	for i := range tcb.builders {
		func(i int, root context.Context) {
			builder := tcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*Test3SchemaMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcb *Test3SchemaCreateBulk) SaveX(ctx context.Context) []*Test3Schema {
	v, err := tcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcb *Test3SchemaCreateBulk) Exec(ctx context.Context) error {
	_, err := tcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcb *Test3SchemaCreateBulk) ExecX(ctx context.Context) {
	if err := tcb.Exec(ctx); err != nil {
		panic(err)
	}
}
