// Code generated by ent, DO NOT EDIT.

package test1schema

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the test1schema type in the database.
	Label = "test1schema"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldFieldString holds the string denoting the field_string field in the database.
	FieldFieldString = "field_string"
	// FieldFieldInt holds the string denoting the field_int field in the database.
	FieldFieldInt = "field_int"
	// FieldFieldFloat holds the string denoting the field_float field in the database.
	FieldFieldFloat = "field_float"
	// FieldFieldBool holds the string denoting the field_bool field in the database.
	FieldFieldBool = "field_bool"
	// FieldFieldTime holds the string denoting the field_time field in the database.
	FieldFieldTime = "field_time"
	// FieldFieldText holds the string denoting the field_text field in the database.
	FieldFieldText = "field_text"
	// Table holds the table name of the test1schema in the database.
	Table = "test1schemas"
)

// Columns holds all SQL columns for test1schema fields.
var Columns = []string{
	FieldID,
	FieldFieldString,
	FieldFieldInt,
	FieldFieldFloat,
	FieldFieldBool,
	FieldFieldTime,
	FieldFieldText,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultFieldString holds the default value on creation for the "field_string" field.
	DefaultFieldString string
	// DefaultFieldInt holds the default value on creation for the "field_int" field.
	DefaultFieldInt int
	// DefaultFieldFloat holds the default value on creation for the "field_float" field.
	DefaultFieldFloat float64
	// DefaultFieldBool holds the default value on creation for the "field_bool" field.
	DefaultFieldBool bool
	// DefaultFieldTime holds the default value on creation for the "field_time" field.
	DefaultFieldTime func() time.Time
)

// OrderOption defines the ordering options for the Test1Schema queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByFieldString orders the results by the field_string field.
func ByFieldString(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFieldString, opts...).ToFunc()
}

// ByFieldInt orders the results by the field_int field.
func ByFieldInt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFieldInt, opts...).ToFunc()
}

// ByFieldFloat orders the results by the field_float field.
func ByFieldFloat(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFieldFloat, opts...).ToFunc()
}

// ByFieldBool orders the results by the field_bool field.
func ByFieldBool(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFieldBool, opts...).ToFunc()
}

// ByFieldTime orders the results by the field_time field.
func ByFieldTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFieldTime, opts...).ToFunc()
}

// ByFieldText orders the results by the field_text field.
func ByFieldText(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFieldText, opts...).ToFunc()
}
