// Code generated by ent, DO NOT EDIT.

package test1schema

import (
	"time"
	"transaction-filter-backend/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldLTE(FieldID, id))
}

// FieldString applies equality check predicate on the "field_string" field. It's identical to FieldStringEQ.
func FieldString(v string) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldEQ(FieldFieldString, v))
}

// FieldInt applies equality check predicate on the "field_int" field. It's identical to FieldIntEQ.
func FieldInt(v int) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldEQ(FieldFieldInt, v))
}

// FieldFloat applies equality check predicate on the "field_float" field. It's identical to FieldFloatEQ.
func FieldFloat(v float64) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldEQ(FieldFieldFloat, v))
}

// FieldBool applies equality check predicate on the "field_bool" field. It's identical to FieldBoolEQ.
func FieldBool(v bool) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldEQ(FieldFieldBool, v))
}

// FieldTime applies equality check predicate on the "field_time" field. It's identical to FieldTimeEQ.
func FieldTime(v time.Time) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldEQ(FieldFieldTime, v))
}

// FieldText applies equality check predicate on the "field_text" field. It's identical to FieldTextEQ.
func FieldText(v string) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldEQ(FieldFieldText, v))
}

// FieldStringEQ applies the EQ predicate on the "field_string" field.
func FieldStringEQ(v string) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldEQ(FieldFieldString, v))
}

// FieldStringNEQ applies the NEQ predicate on the "field_string" field.
func FieldStringNEQ(v string) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldNEQ(FieldFieldString, v))
}

// FieldStringIn applies the In predicate on the "field_string" field.
func FieldStringIn(vs ...string) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldIn(FieldFieldString, vs...))
}

// FieldStringNotIn applies the NotIn predicate on the "field_string" field.
func FieldStringNotIn(vs ...string) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldNotIn(FieldFieldString, vs...))
}

// FieldStringGT applies the GT predicate on the "field_string" field.
func FieldStringGT(v string) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldGT(FieldFieldString, v))
}

// FieldStringGTE applies the GTE predicate on the "field_string" field.
func FieldStringGTE(v string) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldGTE(FieldFieldString, v))
}

// FieldStringLT applies the LT predicate on the "field_string" field.
func FieldStringLT(v string) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldLT(FieldFieldString, v))
}

// FieldStringLTE applies the LTE predicate on the "field_string" field.
func FieldStringLTE(v string) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldLTE(FieldFieldString, v))
}

// FieldStringContains applies the Contains predicate on the "field_string" field.
func FieldStringContains(v string) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldContains(FieldFieldString, v))
}

// FieldStringHasPrefix applies the HasPrefix predicate on the "field_string" field.
func FieldStringHasPrefix(v string) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldHasPrefix(FieldFieldString, v))
}

// FieldStringHasSuffix applies the HasSuffix predicate on the "field_string" field.
func FieldStringHasSuffix(v string) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldHasSuffix(FieldFieldString, v))
}

// FieldStringEqualFold applies the EqualFold predicate on the "field_string" field.
func FieldStringEqualFold(v string) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldEqualFold(FieldFieldString, v))
}

// FieldStringContainsFold applies the ContainsFold predicate on the "field_string" field.
func FieldStringContainsFold(v string) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldContainsFold(FieldFieldString, v))
}

// FieldIntEQ applies the EQ predicate on the "field_int" field.
func FieldIntEQ(v int) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldEQ(FieldFieldInt, v))
}

// FieldIntNEQ applies the NEQ predicate on the "field_int" field.
func FieldIntNEQ(v int) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldNEQ(FieldFieldInt, v))
}

// FieldIntIn applies the In predicate on the "field_int" field.
func FieldIntIn(vs ...int) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldIn(FieldFieldInt, vs...))
}

// FieldIntNotIn applies the NotIn predicate on the "field_int" field.
func FieldIntNotIn(vs ...int) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldNotIn(FieldFieldInt, vs...))
}

// FieldIntGT applies the GT predicate on the "field_int" field.
func FieldIntGT(v int) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldGT(FieldFieldInt, v))
}

// FieldIntGTE applies the GTE predicate on the "field_int" field.
func FieldIntGTE(v int) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldGTE(FieldFieldInt, v))
}

// FieldIntLT applies the LT predicate on the "field_int" field.
func FieldIntLT(v int) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldLT(FieldFieldInt, v))
}

// FieldIntLTE applies the LTE predicate on the "field_int" field.
func FieldIntLTE(v int) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldLTE(FieldFieldInt, v))
}

// FieldFloatEQ applies the EQ predicate on the "field_float" field.
func FieldFloatEQ(v float64) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldEQ(FieldFieldFloat, v))
}

// FieldFloatNEQ applies the NEQ predicate on the "field_float" field.
func FieldFloatNEQ(v float64) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldNEQ(FieldFieldFloat, v))
}

// FieldFloatIn applies the In predicate on the "field_float" field.
func FieldFloatIn(vs ...float64) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldIn(FieldFieldFloat, vs...))
}

// FieldFloatNotIn applies the NotIn predicate on the "field_float" field.
func FieldFloatNotIn(vs ...float64) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldNotIn(FieldFieldFloat, vs...))
}

// FieldFloatGT applies the GT predicate on the "field_float" field.
func FieldFloatGT(v float64) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldGT(FieldFieldFloat, v))
}

// FieldFloatGTE applies the GTE predicate on the "field_float" field.
func FieldFloatGTE(v float64) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldGTE(FieldFieldFloat, v))
}

// FieldFloatLT applies the LT predicate on the "field_float" field.
func FieldFloatLT(v float64) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldLT(FieldFieldFloat, v))
}

// FieldFloatLTE applies the LTE predicate on the "field_float" field.
func FieldFloatLTE(v float64) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldLTE(FieldFieldFloat, v))
}

// FieldBoolEQ applies the EQ predicate on the "field_bool" field.
func FieldBoolEQ(v bool) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldEQ(FieldFieldBool, v))
}

// FieldBoolNEQ applies the NEQ predicate on the "field_bool" field.
func FieldBoolNEQ(v bool) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldNEQ(FieldFieldBool, v))
}

// FieldTimeEQ applies the EQ predicate on the "field_time" field.
func FieldTimeEQ(v time.Time) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldEQ(FieldFieldTime, v))
}

// FieldTimeNEQ applies the NEQ predicate on the "field_time" field.
func FieldTimeNEQ(v time.Time) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldNEQ(FieldFieldTime, v))
}

// FieldTimeIn applies the In predicate on the "field_time" field.
func FieldTimeIn(vs ...time.Time) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldIn(FieldFieldTime, vs...))
}

// FieldTimeNotIn applies the NotIn predicate on the "field_time" field.
func FieldTimeNotIn(vs ...time.Time) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldNotIn(FieldFieldTime, vs...))
}

// FieldTimeGT applies the GT predicate on the "field_time" field.
func FieldTimeGT(v time.Time) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldGT(FieldFieldTime, v))
}

// FieldTimeGTE applies the GTE predicate on the "field_time" field.
func FieldTimeGTE(v time.Time) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldGTE(FieldFieldTime, v))
}

// FieldTimeLT applies the LT predicate on the "field_time" field.
func FieldTimeLT(v time.Time) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldLT(FieldFieldTime, v))
}

// FieldTimeLTE applies the LTE predicate on the "field_time" field.
func FieldTimeLTE(v time.Time) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldLTE(FieldFieldTime, v))
}

// FieldTextEQ applies the EQ predicate on the "field_text" field.
func FieldTextEQ(v string) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldEQ(FieldFieldText, v))
}

// FieldTextNEQ applies the NEQ predicate on the "field_text" field.
func FieldTextNEQ(v string) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldNEQ(FieldFieldText, v))
}

// FieldTextIn applies the In predicate on the "field_text" field.
func FieldTextIn(vs ...string) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldIn(FieldFieldText, vs...))
}

// FieldTextNotIn applies the NotIn predicate on the "field_text" field.
func FieldTextNotIn(vs ...string) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldNotIn(FieldFieldText, vs...))
}

// FieldTextGT applies the GT predicate on the "field_text" field.
func FieldTextGT(v string) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldGT(FieldFieldText, v))
}

// FieldTextGTE applies the GTE predicate on the "field_text" field.
func FieldTextGTE(v string) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldGTE(FieldFieldText, v))
}

// FieldTextLT applies the LT predicate on the "field_text" field.
func FieldTextLT(v string) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldLT(FieldFieldText, v))
}

// FieldTextLTE applies the LTE predicate on the "field_text" field.
func FieldTextLTE(v string) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldLTE(FieldFieldText, v))
}

// FieldTextContains applies the Contains predicate on the "field_text" field.
func FieldTextContains(v string) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldContains(FieldFieldText, v))
}

// FieldTextHasPrefix applies the HasPrefix predicate on the "field_text" field.
func FieldTextHasPrefix(v string) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldHasPrefix(FieldFieldText, v))
}

// FieldTextHasSuffix applies the HasSuffix predicate on the "field_text" field.
func FieldTextHasSuffix(v string) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldHasSuffix(FieldFieldText, v))
}

// FieldTextIsNil applies the IsNil predicate on the "field_text" field.
func FieldTextIsNil() predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldIsNull(FieldFieldText))
}

// FieldTextNotNil applies the NotNil predicate on the "field_text" field.
func FieldTextNotNil() predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldNotNull(FieldFieldText))
}

// FieldTextEqualFold applies the EqualFold predicate on the "field_text" field.
func FieldTextEqualFold(v string) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldEqualFold(FieldFieldText, v))
}

// FieldTextContainsFold applies the ContainsFold predicate on the "field_text" field.
func FieldTextContainsFold(v string) predicate.Test1Schema {
	return predicate.Test1Schema(sql.FieldContainsFold(FieldFieldText, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Test1Schema) predicate.Test1Schema {
	return predicate.Test1Schema(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Test1Schema) predicate.Test1Schema {
	return predicate.Test1Schema(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Test1Schema) predicate.Test1Schema {
	return predicate.Test1Schema(sql.NotPredicates(p))
}
