// Code generated by ent, DO NOT EDIT.

package test2schema

import (
	"time"
	"transaction-filter-backend/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldEQ(FieldDescription, v))
}

// Quantity applies equality check predicate on the "quantity" field. It's identical to QuantityEQ.
func Quantity(v int) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldEQ(FieldQuantity, v))
}

// Price applies equality check predicate on the "price" field. It's identical to PriceEQ.
func Price(v float64) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldEQ(FieldPrice, v))
}

// Active applies equality check predicate on the "active" field. It's identical to ActiveEQ.
func Active(v bool) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldEQ(FieldActive, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldEQ(FieldUpdatedAt, v))
}

// ItemType applies equality check predicate on the "item_type" field. It's identical to ItemTypeEQ.
func ItemType(v string) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldEQ(FieldItemType, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldContainsFold(FieldDescription, v))
}

// QuantityEQ applies the EQ predicate on the "quantity" field.
func QuantityEQ(v int) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldEQ(FieldQuantity, v))
}

// QuantityNEQ applies the NEQ predicate on the "quantity" field.
func QuantityNEQ(v int) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldNEQ(FieldQuantity, v))
}

// QuantityIn applies the In predicate on the "quantity" field.
func QuantityIn(vs ...int) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldIn(FieldQuantity, vs...))
}

// QuantityNotIn applies the NotIn predicate on the "quantity" field.
func QuantityNotIn(vs ...int) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldNotIn(FieldQuantity, vs...))
}

// QuantityGT applies the GT predicate on the "quantity" field.
func QuantityGT(v int) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldGT(FieldQuantity, v))
}

// QuantityGTE applies the GTE predicate on the "quantity" field.
func QuantityGTE(v int) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldGTE(FieldQuantity, v))
}

// QuantityLT applies the LT predicate on the "quantity" field.
func QuantityLT(v int) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldLT(FieldQuantity, v))
}

// QuantityLTE applies the LTE predicate on the "quantity" field.
func QuantityLTE(v int) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldLTE(FieldQuantity, v))
}

// PriceEQ applies the EQ predicate on the "price" field.
func PriceEQ(v float64) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldEQ(FieldPrice, v))
}

// PriceNEQ applies the NEQ predicate on the "price" field.
func PriceNEQ(v float64) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldNEQ(FieldPrice, v))
}

// PriceIn applies the In predicate on the "price" field.
func PriceIn(vs ...float64) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldIn(FieldPrice, vs...))
}

// PriceNotIn applies the NotIn predicate on the "price" field.
func PriceNotIn(vs ...float64) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldNotIn(FieldPrice, vs...))
}

// PriceGT applies the GT predicate on the "price" field.
func PriceGT(v float64) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldGT(FieldPrice, v))
}

// PriceGTE applies the GTE predicate on the "price" field.
func PriceGTE(v float64) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldGTE(FieldPrice, v))
}

// PriceLT applies the LT predicate on the "price" field.
func PriceLT(v float64) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldLT(FieldPrice, v))
}

// PriceLTE applies the LTE predicate on the "price" field.
func PriceLTE(v float64) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldLTE(FieldPrice, v))
}

// ActiveEQ applies the EQ predicate on the "active" field.
func ActiveEQ(v bool) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldEQ(FieldActive, v))
}

// ActiveNEQ applies the NEQ predicate on the "active" field.
func ActiveNEQ(v bool) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldNEQ(FieldActive, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldLTE(FieldUpdatedAt, v))
}

// ItemTypeEQ applies the EQ predicate on the "item_type" field.
func ItemTypeEQ(v string) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldEQ(FieldItemType, v))
}

// ItemTypeNEQ applies the NEQ predicate on the "item_type" field.
func ItemTypeNEQ(v string) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldNEQ(FieldItemType, v))
}

// ItemTypeIn applies the In predicate on the "item_type" field.
func ItemTypeIn(vs ...string) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldIn(FieldItemType, vs...))
}

// ItemTypeNotIn applies the NotIn predicate on the "item_type" field.
func ItemTypeNotIn(vs ...string) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldNotIn(FieldItemType, vs...))
}

// ItemTypeGT applies the GT predicate on the "item_type" field.
func ItemTypeGT(v string) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldGT(FieldItemType, v))
}

// ItemTypeGTE applies the GTE predicate on the "item_type" field.
func ItemTypeGTE(v string) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldGTE(FieldItemType, v))
}

// ItemTypeLT applies the LT predicate on the "item_type" field.
func ItemTypeLT(v string) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldLT(FieldItemType, v))
}

// ItemTypeLTE applies the LTE predicate on the "item_type" field.
func ItemTypeLTE(v string) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldLTE(FieldItemType, v))
}

// ItemTypeContains applies the Contains predicate on the "item_type" field.
func ItemTypeContains(v string) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldContains(FieldItemType, v))
}

// ItemTypeHasPrefix applies the HasPrefix predicate on the "item_type" field.
func ItemTypeHasPrefix(v string) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldHasPrefix(FieldItemType, v))
}

// ItemTypeHasSuffix applies the HasSuffix predicate on the "item_type" field.
func ItemTypeHasSuffix(v string) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldHasSuffix(FieldItemType, v))
}

// ItemTypeIsNil applies the IsNil predicate on the "item_type" field.
func ItemTypeIsNil() predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldIsNull(FieldItemType))
}

// ItemTypeNotNil applies the NotNil predicate on the "item_type" field.
func ItemTypeNotNil() predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldNotNull(FieldItemType))
}

// ItemTypeEqualFold applies the EqualFold predicate on the "item_type" field.
func ItemTypeEqualFold(v string) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldEqualFold(FieldItemType, v))
}

// ItemTypeContainsFold applies the ContainsFold predicate on the "item_type" field.
func ItemTypeContainsFold(v string) predicate.Test2Schema {
	return predicate.Test2Schema(sql.FieldContainsFold(FieldItemType, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Test2Schema) predicate.Test2Schema {
	return predicate.Test2Schema(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Test2Schema) predicate.Test2Schema {
	return predicate.Test2Schema(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Test2Schema) predicate.Test2Schema {
	return predicate.Test2Schema(sql.NotPredicates(p))
}
