// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Test1Schema is the predicate function for test1schema builders.
type Test1Schema func(*sql.Selector)

// Test2Schema is the predicate function for test2schema builders.
type Test2Schema func(*sql.Selector)

// Test3Schema is the predicate function for test3schema builders.
type Test3Schema func(*sql.Selector)

// Transaction is the predicate function for transaction builders.
type Transaction func(*sql.Selector)
